# Generated by Django 5.1.5 on 2025-02-03 08:49

import api.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, upload_to='pfp/')),
                ('location', models.CharField(choices=[('COL0', 'Colombo'), ('COL1', 'Kolonnawa'), ('COL2', 'Kaduwela'), ('COL3', 'Homagama'), ('COL4', 'Seethawaka'), ('COL5', 'Padukka'), ('COL6', 'Maharagama'), ('COL7', 'Sri Jayawardanapura Kotte'), ('COL8', 'Thimbirigasyaya'), ('COL9', 'Dehiwala'), ('COL10', 'Ratmalana'), ('COL11', 'Moratuwa'), ('COL12', 'Kesbewa'), ('GAM0', 'Negombo'), ('GAM1', 'Katana'), ('GAM2', 'Divulapitiya'), ('GAM3', 'Mirigama'), ('GAM4', 'Minuwangoda'), ('GAM5', 'Wattala'), ('GAM6', 'Ja-Ela'), ('GAM7', 'Gampaha'), ('GAM8', 'Attanagalla'), ('GAM9', 'Dompe'), ('GAM10', 'Mahara'), ('GAM11', 'Kelaniya'), ('GAM12', 'Biyagama'), ('KAL0', 'Panadura'), ('KAL1', 'Bandaragama'), ('KAL2', 'Horana'), ('KAL3', 'Ingiriya'), ('KAL4', 'Bulathsinhala'), ('KAL5', 'Madurawala'), ('KAL6', 'Millaniya'), ('KAL7', 'Kalutara'), ('KAL8', 'Beruwala'), ('KAL9', 'Dodangoda'), ('KAL10', 'Mathugama'), ('KAL11', 'Agalawatta'), ('KAL12', 'Palindanuwara'), ('KAL13', 'Walallawita'), ('KAN0', 'Thumpane'), ('KAN1', 'Pujapitiya'), ('KAN2', 'Akurana'), ('KAN3', 'Pathadumbara'), ('KAN4', 'Panvila'), ('KAN5', 'Udadumbara'), ('KAN6', 'Minipe'), ('KAN7', 'Medadumbara'), ('KAN8', 'Kundasale'), ('KAN9', 'Kandy Four Gravets & Gangawata Korale'), ('KAN10', 'Harispattuwa'), ('KAN11', 'Hatharaliyadda'), ('KAN12', 'Yatinuwara'), ('KAN13', 'Udunuwara'), ('KAN14', 'Doluwa'), ('KAN15', 'Pathahewaheta'), ('KAN16', 'Delthota'), ('KAN17', 'Udapalatha'), ('KAN18', 'Ganga Ihala Korale'), ('KAN19', 'Pasbage Korale'), ('MAT0', 'Galewela'), ('MAT1', 'Dambulla'), ('MAT2', 'Naula'), ('MAT3', 'Pallepola'), ('MAT4', 'Yatawatta '), ('MAT5', 'Yatawatta'), ('MAT6', 'Matale'), ('MAT7', 'Ambanganga Korale'), ('MAT8', 'Laggala-Pallegama'), ('MAT9', 'Wilgamuwa'), ('MAT10', 'Rattota'), ('MAT11', 'Ukuwela'), ('NUW0', 'Kothmale'), ('NUW1', 'Hanguranketha'), ('NUW2', 'Walapane'), ('NUW3', 'Nuwara Eliya'), ('NUW4', 'Ambagamuwa'), ('GAL0', 'Bentota'), ('GAL1', 'Balapitiya'), ('GAL2', 'Karandeniya'), ('GAL3', 'Elpitiya'), ('GAL4', 'Niyagama'), ('GAL5', 'Thawalama'), ('GAL6', 'Neluwa'), ('GAL7', 'Nagoda'), ('GAL8', 'Baddegama'), ('GAL9', 'Wanduramba'), ('GAL10', 'Welivitiya-Divithura'), ('GAL11', 'Ambalangoda'), ('GAL12', 'Gonapeenuwala'), ('GAL13', 'Madampagama'), ('GAL14', 'Hikkaduwa'), ('GAL15', 'Rathgama'), ('GAL16', 'Galle Four Gravets'), ('GAL17', 'Bope-Poddala'), ('GAL18', 'Akmeemana'), ('GAL19', 'Yakkalamulla'), ('GAL20', 'Imaduwa'), ('GAL21', 'Habaraduwa'), ('MTA0', 'Pitabeddara'), ('MTA1', 'Kotapola'), ('MTA2', 'Pasgoda'), ('MTA3', 'Mulatiyana'), ('MTA4', 'Athuraliya'), ('MTA5', 'Akurassa'), ('MTA6', 'Welipitiya'), ('MTA7', 'Malimbada'), ('MTA8', 'Kamburupitiya'), ('MTA9', 'Hakmana'), ('MTA10', 'Kirinda -Puhulwella'), ('MTA11', 'Thihagoda'), ('MTA12', 'Weligama'), ('MTA13', 'Matara Four Gravets'), ('MTA14', 'Devinuwara'), ('MTA15', 'Dickwella'), ('HAM0', 'Sooriyawewa'), ('HAM1', 'Lunugamvehera'), ('HAM2', 'Thissamaharama'), ('HAM3', 'Tissamaharamaya'), ('HAM4', 'Hambantota'), ('HAM5', 'Ambalantota'), ('HAM6', 'Angunakolapelessa'), ('HAM7', 'Weeraketiya'), ('HAM8', 'Katuwana'), ('HAM9', 'Walasmulla'), ('HAM10', 'Okewela'), ('HAM11', 'Beliatta'), ('HAM12', 'Tangalle'), ('JAF0', 'Island North (Kayts)'), ('JAF1', 'Karainagar'), ('JAF2', 'Valikamam West'), ('JAF3', 'Valikamam South West (Sandilipay)'), ('JAF4', 'Valikamam North'), ('JAF5', 'Valikamam South (Uduvil)'), ('JAF6', 'Valikamam East (Kopay)'), ('JAF7', 'Vadamaradchi South-West (Karaveddy)'), ('JAF8', 'Vadamaradchy East'), ('JAF9', 'Vadamaradchi North (Point Pedro)'), ('JAF10', 'Thenmaradchi'), ('JAF11', 'Nallur'), ('JAF12', 'Jaffna'), ('JAF13', 'Island South (Velanai)'), ('JAF14', 'Delft'), ('MAN0', 'Mannar Town'), ('MAN1', 'Manthai West'), ('MAN2', 'Madhu'), ('MAN3', 'Nanattan'), ('MAN4', 'Musali'), ('VAV0', 'Vavuniya North'), ('VAV1', 'Vavuniya South'), ('VAV2', 'Vavuniya Town'), ('VAV3', 'Vengalacheddikulam'), ('MUL0', 'Thunukkai'), ('MUL1', 'Manthai East'), ('MUL2', 'Puthukudiyiruppu'), ('MUL3', 'Oddusuddan'), ('MUL4', 'Meritimepattu'), ('MUL5', 'Welioya'), ('KIL0', 'Pachchilaipalli'), ('KIL1', 'Kandawalai'), ('KIL2', 'Karachchi'), ('KIL3', 'Poonakary'), ('BAT0', 'Koralai Pattu North (Vaharai)'), ('BAT1', 'Koralai Pattu Central'), ('BAT2', 'Koralaipattu West (Oddamavadi)'), ('BAT3', 'Koralai Pattu(Valachchenai)'), ('BAT4', 'Koralai Pattu South (Kiran)'), ('BAT5', 'Eravur Pattu'), ('BAT6', 'Eravur Town'), ('BAT7', 'Manmunai North'), ('BAT8', 'Manmunai West'), ('BAT9', 'Kattankudy'), ('BAT10', 'Manmunai Pattu(Araipattai)'), ('BAT11', 'Manmunai South-West'), ('BAT12', 'Poratheevu Pattu'), ('BAT13', 'Pratheevu Pattu'), ('BAT14', 'Manmunai South & Eruvil pattu'), ('AMP0', 'Dehiattakandiya'), ('AMP1', 'Padiyathalawa'), ('AMP2', 'Mahaoya'), ('AMP3', 'Uhana'), ('AMP4', 'Ampara'), ('AMP5', 'Navithanveli'), ('AMP6', 'Sammanthurai'), ('AMP7', 'Kalmunai Tamil Division'), ('AMP8', 'Kalmunai'), ('AMP9', 'Sainthamaruthu'), ('AMP10', 'Karaitheevu'), ('AMP11', 'Ninthavur'), ('AMP12', 'Addalachchenai'), ('AMP13', 'Irakkamam'), ('AMP14', 'Akkaraipattu'), ('AMP15', 'Akkaraipattu '), ('AMP16', 'Alayadiwembu'), ('AMP17', 'Damana'), ('AMP18', 'Thirukkovil'), ('AMP19', 'Pottuvil'), ('AMP20', 'Lahugala'), ('TRI0', 'Padavisiripura'), ('TRI1', 'Kuchchaveli'), ('TRI2', 'Gomarankadawala'), ('TRI3', 'Morawewa'), ('TRI4', 'Trincomalee Town and Gravets'), ('TRI5', 'Thambalagamuwa'), ('TRI6', 'Kanthale'), ('TRI7', 'Kinniya'), ('TRI8', 'Muttur'), ('TRI9', 'Seruvila'), ('TRI10', 'Verugal(Eachchilampattu)'), ('KUR0', 'Giribawa'), ('KUR1', 'Galgamuwa'), ('KUR2', 'Ehetuwewa'), ('KUR3', 'Ambanpola'), ('KUR4', 'Kotavehera'), ('KUR5', 'Rasnayakapura'), ('KUR6', 'Nikaweratiya'), ('KUR7', 'Maho'), ('KUR8', 'Polpithigama'), ('KUR9', 'Ibbagamuwa'), ('KUR10', 'Ganewatta'), ('KUR11', 'Wariyapola'), ('KUR12', 'Kobeigane'), ('KUR13', 'Bingiriya'), ('KUR14', 'Panduwasnuwara West'), ('KUR15', 'Panduwasnuwara East'), ('KUR16', 'Bamunakotuwa'), ('KUR17', 'Maspotha'), ('KUR18', 'Kurunegala'), ('KUR19', 'Mallawapitiya'), ('KUR20', 'Mawathagama'), ('KUR21', 'Mawathagama '), ('KUR22', 'Rideegama'), ('KUR23', 'Weerambugedara'), ('KUR24', 'Kuliyapitiya East'), ('KUR25', 'Kuliyapitiya West'), ('KUR26', 'Udubaddawa'), ('KUR27', 'Pannala'), ('KUR28', 'Narammala'), ('KUR29', 'Alawwa'), ('KUR30', 'Polgahawela'), ('PUT0', 'Kalpitiya'), ('PUT1', 'Vanathawilluwa'), ('PUT2', 'Karuwalagaswewa'), ('PUT3', 'Nawagattegama'), ('PUT4', 'Puttalam'), ('PUT5', 'Mundel'), ('PUT6', 'Mahakumbukkadawala'), ('PUT7', 'Anamaduwa'), ('PUT8', 'Pallama'), ('PUT9', 'Arachchikattuwa'), ('PUT10', 'Chilaw'), ('PUT11', 'Madampe'), ('PUT12', 'Mahawewa'), ('PUT13', 'Nattandiya'), ('PUT14', 'Wennappuwa'), ('PUT15', 'Dankotuwa'), ('ANU0', 'Padaviya'), ('ANU1', 'Kebithigollewa'), ('ANU2', 'Madawachchiya'), ('ANU3', 'Medawachchiya'), ('ANU4', 'Mahawilachchiya'), ('ANU5', 'Nuwaragam Palatha Central'), ('ANU6', 'Rambewa'), ('ANU7', 'Kahatagasdigiliya'), ('ANU8', 'Horowpothana'), ('ANU9', 'Galenbindunuwewa'), ('ANU10', 'Mihinthale'), ('ANU11', 'Nuwaragam Palatha East'), ('ANU12', 'Nachchadoowa'), ('ANU13', 'Nochchiyagama'), ('ANU14', 'Rajanganaya'), ('ANU15', 'Thambuttegama'), ('ANU16', 'Thalawa'), ('ANU17', 'Thirappane'), ('ANU18', 'Kekirawa'), ('ANU19', 'Palugaswewa'), ('ANU20', 'Ipalogama'), ('ANU21', 'Galnewa'), ('ANU22', 'Palagala'), ('POL0', 'Hingurakgoda'), ('POL1', 'Medirigiriya'), ('POL2', 'Lankapura'), ('POL3', 'Welikanda'), ('POL4', 'Welkanda'), ('POL5', 'Dimbulagala'), ('POL6', 'Thamankaduwa'), ('POL7', 'Elahera'), ('BAD0', 'Mahiyanganaya'), ('BAD1', 'Rideemaliyadda'), ('BAD2', 'Meegahakivula'), ('BAD3', 'Kandeketiya'), ('BAD4', 'Soranathota'), ('BAD5', 'Passara'), ('BAD6', 'Lunugala'), ('BAD7', 'Badulla'), ('BAD8', 'Hali Ela'), ('BAD9', 'Uva Paranagama'), ('BAD10', 'Welimada'), ('BAD11', 'Bandarawela'), ('BAD12', 'Ella'), ('BAD13', 'Haputale'), ('BAD14', 'Haputale '), ('BAD15', 'Haldummulla'), ('MON0', 'Bibile'), ('MON1', 'Madulla'), ('MON2', 'Medagama'), ('MON3', 'Siyambalanduwa'), ('MON4', 'Moneragala'), ('MON5', 'Badalkumbura'), ('MON6', 'Wellawaya'), ('MON7', 'Buttala'), ('MON8', 'Katharagama'), ('MON9', 'Thanamalvila'), ('MON10', 'Sevanagala'), ('RAT0', 'Eheliyagoda'), ('RAT1', 'Kuruvita'), ('RAT2', 'Kiriella'), ('RAT3', 'Kiiriella'), ('RAT4', 'Ratnapura'), ('RAT5', 'Imbulpe'), ('RAT6', 'Balangoda'), ('RAT7', 'Kalthota'), ('RAT8', 'Opanayaka'), ('RAT9', 'Pelmadulla'), ('RAT10', 'Elapatha'), ('RAT11', 'Ayagama'), ('RAT12', 'Kalawana'), ('RAT13', 'Nivitigala'), ('RAT14', 'Kahawatta'), ('RAT15', 'Godakawela'), ('RAT16', 'Weligepola'), ('RAT17', 'Embilipitiya'), ('RAT18', 'Kolonna'), ('KEG0', 'Rambukkana'), ('KEG1', 'Mawanella'), ('KEG2', 'Aranayaka'), ('KEG3', 'Kegalle'), ('KEG4', 'Galigamuwa'), ('KEG5', 'Warakapola'), ('KEG6', 'Ruwanwella'), ('KEG7', 'Bulathkohupitiya'), ('KEG8', 'Yatiyanthota'), ('KEG9', 'Dehiovita'), ('KEG10', 'Deraniyagala')], max_length=10)),
                ('fb_account', models.URLField(blank=True, validators=[api.validators.validate_fb_url])),
                ('ig_account', models.URLField(blank=True, validators=[api.validators.validate_ig_url])),
                ('mod_status', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reachouts', models.IntegerField(default=0)),
                ('recommendations', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('giftreqs', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelperRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_type', models.CharField(max_length=100)),
                ('serv_desc', models.CharField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=500)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.posts')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
