# Generated by Django 5.1.5 on 2025-02-02 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fb_account',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(regex='(\\A(https://www\\.facebook\\.com/profile\\.php\\?id=)[0-9]+)|(\\A(https://www\\.facebook\\.com/)[^\\/]+)')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='ig_account',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(regex='(\\A(https://www\\.instagram\\.com/profile\\.php\\?id=)[0-9]+)')]),
        ),
    ]
