# Generated by Django 5.1.5 on 2025-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_fb_account_alter_myuser_ig_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mod_status',
            field=models.BooleanField(default=False),
        ),
    ]
