# Generated by Django 5.1.5 on 2025-02-02 11:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myuser_mod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fb_account',
            field=models.URLField(blank=True, validators=[api.models.validate_fb_url]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='ig_account',
            field=models.URLField(blank=True, validators=[api.models.validate_ig_url]),
        ),
    ]
