# Generated by Django 5.1.5 on 2025-02-05 16:15

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='images',
            field=models.ImageField(blank=True, upload_to='', validators=[api.validators.ImageValidation]),
        ),
    ]
