# Generated by Django 5.1.5 on 2025-02-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gifts_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
