# Generated by Django 5.1.5 on 2025-02-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='userid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
