# Generated by Django 5.1.5 on 2025-02-02 20:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_engagementmetrics_gifts_helperrole_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='', validators=[api.validators.pfp_validator]),
        ),
    ]
