# Generated by Django 5.1.5 on 2025-02-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gifts_userid_alter_posts_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementmetrics',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gifts',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='helperrole',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='userid',
            new_name='user',
        ),
    ]
