# Generated by Django 5.1.5 on 2025-02-07 10:58

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_userid_engagementmetrics_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='images',
            field=models.ImageField(blank=True, upload_to='giftreq_images/', validators=[api.validators.ImageValidation]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, upload_to='post_images/', validators=[api.validators.ImageValidation]),
        ),
    ]
