# Generated by Django 5.1.5 on 2025-02-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gifts_images_alter_posts_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
