# Generated by Django 5.1.5 on 2025-02-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gifts_tags_alter_gifts_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
