# Generated by Django 5.1.5 on 2025-02-08 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_myuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementmetrics',
            old_name='giftreqs',
            new_name='giftreq_count',
        ),
        migrations.RenameField(
            model_name='engagementmetrics',
            old_name='posts',
            new_name='post_count',
        ),
        migrations.RenameField(
            model_name='engagementmetrics',
            old_name='reachouts',
            new_name='reachout_count',
        ),
        migrations.RenameField(
            model_name='engagementmetrics',
            old_name='replies',
            new_name='reply_count',
        ),
        migrations.RenameField(
            model_name='gifts',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='postid',
        ),
        migrations.AddField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.posts'),
        ),
        migrations.AlterField(
            model_name='engagementmetrics',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helperrole',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replies',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
