# Generated by Django 5.1.5 on 2025-02-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_giftreqs_engagementmetrics_giftreq_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.posts'),
        ),
    ]
