# Generated by Django 5.1.5 on 2025-02-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_replies_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.posts'),
        ),
    ]
