# Generated by Django 5.1.5 on 2025-02-11 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_replies_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementmetrics',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helperrole',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='helper_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
