# Generated by Django 5.1.5 on 2025-02-13 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_engagementmetrics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementmetrics',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL),
        ),
    ]
