// export const locations = [
// {value:"COL0" , name:"Colombo"},
// {value:"COL1" , name:"Kolonnawa"},
// {value:"COL2" , name:"Kaduwela"},
// {value:"COL3" , name:"Homagama"},
// {value:"COL4" , name:"Seethawaka"},
// {value:"COL5" , name:"Padukka"},
// {value:"COL6" , name:"Maharagama"},
// {value:"COL7" , name:"Sri Jayawardanapura Kotte"},
// {value:"COL8" , name:"Thimbirigasyaya"},
// {value:"COL9" , name:"Dehiwala"},
// {value:"COL10" , name:"Ratmalana"},
// {value:"COL11" , name:"Moratuwa"},
// {value:"COL12" , name:"Kesbewa"},
// {value:"GAM0" , name:"Negombo"},
// {value:"GAM1" , name:"Katana"},
// {value:"GAM2" , name:"Divulapitiya"},
// {value:"GAM3" , name:"Mirigama"},
// {value:"GAM4" , name:"Minuwangoda"},
// {value:"GAM5" , name:"Wattala"},
// {value:"GAM6" , name:"Ja-Ela"},
// {value:"GAM7" , name:"Gampaha"},
// {value:"GAM8" , name:"Attanagalla"},
// {value:"GAM9" , name:"Dompe"},
// {value:"GAM10" , name:"Mahara"},
// {value:"GAM11" , name:"Kelaniya"},
// {value:"GAM12" , name:"Biyagama"},
// {value:"KAL0" , name:"Panadura"},
// {value:"KAL1" , name:"Bandaragama"},
// {value:"KAL2" , name:"Horana"},
// {value:"KAL3" , name:"Ingiriya"},
// {value:"KAL4" , name:"Bulathsinhala"},
// {value:"KAL5" , name:"Madurawala"},
// {value:"KAL6" , name:"Millaniya"},
// {value:"KAL7" , name:"Kalutara"},
// {value:"KAL8" , name:"Beruwala"},
// {value:"KAL9" , name:"Dodangoda"},
// {value:"KAL10" , name:"Mathugama"},
// {value:"KAL11" , name:"Agalawatta"},
// {value:"KAL12" , name:"Palindanuwara"},
// {value:"KAL13" , name:"Walallawita"},
// {value:"KAN0" , name:"Thumpane"},
// {value:"KAN1" , name:"Pujapitiya"},
// {value:"KAN2" , name:"Akurana"},
// {value:"KAN3" , name:"Pathadumbara"},
// {value:"KAN4" , name:"Panvila"},
// {value:"KAN5" , name:"Udadumbara"},
// {value:"KAN6" , name:"Minipe"},
// {value:"KAN7" , name:"Medadumbara"},
// {value:"KAN8" , name:"Kundasale"},
// {value:"KAN9" , name:"Kandy Four Gravets & Gangawata Korale"},
// {value:"KAN10" , name:"Harispattuwa"},
// {value:"KAN11" , name:"Hatharaliyadda"},
// {value:"KAN12" , name:"Yatinuwara"},
// {value:"KAN13" , name:"Udunuwara"},
// {value:"KAN14" , name:"Doluwa"},
// {value:"KAN15" , name:"Pathahewaheta"},
// {value:"KAN16" , name:"Delthota"},
// {value:"KAN17" , name:"Udapalatha"},
// {value:"KAN18" , name:"Ganga Ihala Korale"},
// {value:"KAN19" , name:"Pasbage Korale"},
// {value:"MAT0" , name:"Galewela"},
// {value:"MAT1" , name:"Dambulla"},
// {value:"MAT2" , name:"Naula"},
// {value:"MAT3" , name:"Pallepola"},
// {value:"MAT4" , name:"Yatawatta "},
// {value:"MAT5" , name:"Yatawatta"},
// {value:"MAT6" , name:"Matale"},
// {value:"MAT7" , name:"Ambanganga Korale"},
// {value:"MAT8" , name:"Laggala-Pallegama"},
// {value:"MAT9" , name:"Wilgamuwa"},
// {value:"MAT10" , name:"Rattota"},
// {value:"MAT11" , name:"Ukuwela"},
// {value:"NUW0" , name:"Kothmale"},
// {value:"NUW1" , name:"Hanguranketha"},
// {value:"NUW2" , name:"Walapane"},
// {value:"NUW3" , name:"Nuwara Eliya"},
// {value:"NUW4" , name:"Ambagamuwa"},
// {value:"GAL0" , name:"Bentota"},
// {value:"GAL1" , name:"Balapitiya"},
// {value:"GAL2" , name:"Karandeniya"},
// {value:"GAL3" , name:"Elpitiya"},
// {value:"GAL4" , name:"Niyagama"},
// {value:"GAL5" , name:"Thawalama"},
// {value:"GAL6" , name:"Neluwa"},
// {value:"GAL7" , name:"Nagoda"},
// {value:"GAL8" , name:"Baddegama"},
// {value:"GAL9" , name:"Wanduramba"},
// {value:"GAL10" , name:"Welivitiya-Divithura"},
// {value:"GAL11" , name:"Ambalangoda"},
// {value:"GAL12" , name:"Gonapeenuwala"},
// {value:"GAL13" , name:"Madampagama"},
// {value:"GAL14" , name:"Hikkaduwa"},
// {value:"GAL15" , name:"Rathgama"},
// {value:"GAL16" , name:"Galle Four Gravets"},
// {value:"GAL17" , name:"Bope-Poddala"},
// {value:"GAL18" , name:"Akmeemana"},
// {value:"GAL19" , name:"Yakkalamulla"},
// {value:"GAL20" , name:"Imaduwa"},
// {value:"GAL21" , name:"Habaraduwa"},
// {value:"MTA0" , name:"Pitabeddara"},
// {value:"MTA1" , name:"Kotapola"},
// {value:"MTA2" , name:"Pasgoda"},
// {value:"MTA3" , name:"Mulatiyana"},
// {value:"MTA4" , name:"Athuraliya"},
// {value:"MTA5" , name:"Akurassa"},
// {value:"MTA6" , name:"Welipitiya"},
// {value:"MTA7" , name:"Malimbada"},
// {value:"MTA8" , name:"Kamburupitiya"},
// {value:"MTA9" , name:"Hakmana"},
// {value:"MTA10" , name:"Kirinda -Puhulwella"},
// {value:"MTA11" , name:"Thihagoda"},
// {value:"MTA12" , name:"Weligama"},
// {value:"MTA13" , name:"Matara Four Gravets"},
// {value:"MTA14" , name:"Devinuwara"},
// {value:"MTA15" , name:"Dickwella"},
// {value:"HAM0" , name:"Sooriyawewa"},
// {value:"HAM1" , name:"Lunugamvehera"},
// {value:"HAM2" , name:"Thissamaharama"},
// {value:"HAM3" , name:"Tissamaharamaya"},
// {value:"HAM4" , name:"Hambantota"},
// {value:"HAM5" , name:"Ambalantota"},
// {value:"HAM6" , name:"Angunakolapelessa"},
// {value:"HAM7" , name:"Weeraketiya"},
// {value:"HAM8" , name:"Katuwana"},
// {value:"HAM9" , name:"Walasmulla"},
// {value:"HAM10" , name:"Okewela"},
// {value:"HAM11" , name:"Beliatta"},
// {value:"HAM12" , name:"Tangalle"},
// {value:"JAF0" , name:"Island North (Kayts)"},
// {value:"JAF1" , name:"Karainagar"},
// {value:"JAF2" , name:"Valikamam West"},
// {value:"JAF3" , name:"Valikamam South West (Sandilipay)"},
// {value:"JAF4" , name:"Valikamam North"},
// {value:"JAF5" , name:"Valikamam South (Uduvil)"},
// {value:"JAF6" , name:"Valikamam East (Kopay)"},
// {value:"JAF7" , name:"Vadamaradchi South-West (Karaveddy)"},
// {value:"JAF8" , name:"Vadamaradchy East"},
// {value:"JAF9" , name:"Vadamaradchi North (Point Pedro)"},
// {value:"JAF10" , name:"Thenmaradchi"},
// {value:"JAF11" , name:"Nallur"},
// {value:"JAF12" , name:"Jaffna"},
// {value:"JAF13" , name:"Island South (Velanai)"},
// {value:"JAF14" , name:"Delft"},
// {value:"MAN0" , name:"Mannar Town"},
// {value:"MAN1" , name:"Manthai West"},
// {value:"MAN2" , name:"Madhu"},
// {value:"MAN3" , name:"Nanattan"},
// {value:"MAN4" , name:"Musali"},
// {value:"VAV0" , name:"Vavuniya North"},
// {value:"VAV1" , name:"Vavuniya South"},
// {value:"VAV2" , name:"Vavuniya Town"},
// {value:"VAV3" , name:"Vengalacheddikulam"},
// {value:"MUL0" , name:"Thunukkai"},
// {value:"MUL1" , name:"Manthai East"},
// {value:"MUL2" , name:"Puthukudiyiruppu"},
// {value:"MUL3" , name:"Oddusuddan"},
// {value:"MUL4" , name:"Meritimepattu"},
// {value:"MUL5" , name:"Welioya"},
// {value:"KIL0" , name:"Pachchilaipalli"},
// {value:"KIL1" , name:"Kandawalai"},
// {value:"KIL2" , name:"Karachchi"},
// {value:"KIL3" , name:"Poonakary"},
// {value:"BAT0" , name:"Koralai Pattu North (Vaharai)"},
// {value:"BAT1" , name:"Koralai Pattu Central"},
// {value:"BAT2" , name:"Koralaipattu West (Oddamavadi)"},
// {value:"BAT3" , name:"Koralai Pattu(Valachchenai)"},
// {value:"BAT4" , name:"Koralai Pattu South (Kiran)"},
// {value:"BAT5" , name:"Eravur Pattu"},
// {value:"BAT6" , name:"Eravur Town"},
// {value:"BAT7" , name:"Manmunai North"},
// {value:"BAT8" , name:"Manmunai West"},
// {value:"BAT9" , name:"Kattankudy"},
// {value:"BAT10" , name:"Manmunai Pattu(Araipattai)"},
// {value:"BAT11" , name:"Manmunai South-West"},
// {value:"BAT12" , name:"Poratheevu Pattu"},
// {value:"BAT13" , name:"Pratheevu Pattu"},
// {value:"BAT14" , name:"Manmunai South & Eruvil pattu"},
// {value:"AMP0" , name:"Dehiattakandiya"},
// {value:"AMP1" , name:"Padiyathalawa"},
// {value:"AMP2" , name:"Mahaoya"},
// {value:"AMP3" , name:"Uhana"},
// {value:"AMP4" , name:"Ampara"},
// {value:"AMP5" , name:"Navithanveli"},
// {value:"AMP6" , name:"Sammanthurai"},
// {value:"AMP7" , name:"Kalmunai Tamil Division"},
// {value:"AMP8" , name:"Kalmunai"},
// {value:"AMP9" , name:"Sainthamaruthu"},
// {value:"AMP10" , name:"Karaitheevu"},
// {value:"AMP11" , name:"Ninthavur"},
// {value:"AMP12" , name:"Addalachchenai"},
// {value:"AMP13" , name:"Irakkamam"},
// {value:"AMP14" , name:"Akkaraipattu"},
// {value:"AMP15" , name:"Akkaraipattu "},
// {value:"AMP16" , name:"Alayadiwembu"},
// {value:"AMP17" , name:"Damana"},
// {value:"AMP18" , name:"Thirukkovil"},
// {value:"AMP19" , name:"Pottuvil"},
// {value:"AMP20" , name:"Lahugala"},
// {value:"TRI0" , name:"Padavisiripura"},
// {value:"TRI1" , name:"Kuchchaveli"},
// {value:"TRI2" , name:"Gomarankadawala"},
// {value:"TRI3" , name:"Morawewa"},
// {value:"TRI4" , name:"Trincomalee Town and Gravets"},
// {value:"TRI5" , name:"Thambalagamuwa"},
// {value:"TRI6" , name:"Kanthale"},
// {value:"TRI7" , name:"Kinniya"},
// {value:"TRI8" , name:"Muttur"},
// {value:"TRI9" , name:"Seruvila"},
// {value:"TRI10" , name:"Verugal(Eachchilampattu)"},
// {value:"KUR0" , name:"Giribawa"},
// {value:"KUR1" , name:"Galgamuwa"},
// {value:"KUR2" , name:"Ehetuwewa"},
// {value:"KUR3" , name:"Ambanpola"},
// {value:"KUR4" , name:"Kotavehera"},
// {value:"KUR5" , name:"Rasnayakapura"},
// {value:"KUR6" , name:"Nikaweratiya"},
// {value:"KUR7" , name:"Maho"},
// {value:"KUR8" , name:"Polpithigama"},
// {value:"KUR9" , name:"Ibbagamuwa"},
// {value:"KUR10" , name:"Ganewatta"},
// {value:"KUR11" , name:"Wariyapola"},
// {value:"KUR12" , name:"Kobeigane"},
// {value:"KUR13" , name:"Bingiriya"},
// {value:"KUR14" , name:"Panduwasnuwara West"},
// {value:"KUR15" , name:"Panduwasnuwara East"},
// {value:"KUR16" , name:"Bamunakotuwa"},
// {value:"KUR17" , name:"Maspotha"},
// {value:"KUR18" , name:"Kurunegala"},
// {value:"KUR19" , name:"Mallawapitiya"},
// {value:"KUR20" , name:"Mawathagama"},
// {value:"KUR21" , name:"Mawathagama "},
// {value:"KUR22" , name:"Rideegama"},
// {value:"KUR23" , name:"Weerambugedara"},
// {value:"KUR24" , name:"Kuliyapitiya East"},
// {value:"KUR25" , name:"Kuliyapitiya West"},
// {value:"KUR26" , name:"Udubaddawa"},
// {value:"KUR27" , name:"Pannala"},
// {value:"KUR28" , name:"Narammala"},
// {value:"KUR29" , name:"Alawwa"},
// {value:"KUR30" , name:"Polgahawela"},
// {value:"PUT0" , name:"Kalpitiya"},
// {value:"PUT1" , name:"Vanathawilluwa"},
// {value:"PUT2" , name:"Karuwalagaswewa"},
// {value:"PUT3" , name:"Nawagattegama"},
// {value:"PUT4" , name:"Puttalam"},
// {value:"PUT5" , name:"Mundel"},
// {value:"PUT6" , name:"Mahakumbukkadawala"},
// {value:"PUT7" , name:"Anamaduwa"},
// {value:"PUT8" , name:"Pallama"},
// {value:"PUT9" , name:"Arachchikattuwa"},
// {value:"PUT10" , name:"Chilaw"},
// {value:"PUT11" , name:"Madampe"},
// {value:"PUT12" , name:"Mahawewa"},
// {value:"PUT13" , name:"Nattandiya"},
// {value:"PUT14" , name:"Wennappuwa"},
// {value:"PUT15" , name:"Dankotuwa"},
// {value:"ANU0" , name:"Padaviya"},
// {value:"ANU1" , name:"Kebithigollewa"},
// {value:"ANU2" , name:"Madawachchiya"},
// {value:"ANU3" , name:"Medawachchiya"},
// {value:"ANU4" , name:"Mahawilachchiya"},
// {value:"ANU5" , name:"Nuwaragam Palatha Central"},
// {value:"ANU6" , name:"Rambewa"},
// {value:"ANU7" , name:"Kahatagasdigiliya"},
// {value:"ANU8" , name:"Horowpothana"},
// {value:"ANU9" , name:"Galenbindunuwewa"},
// {value:"ANU10" , name:"Mihinthale"},
// {value:"ANU11" , name:"Nuwaragam Palatha East"},
// {value:"ANU12" , name:"Nachchadoowa"},
// {value:"ANU13" , name:"Nochchiyagama"},
// {value:"ANU14" , name:"Rajanganaya"},
// {value:"ANU15" , name:"Thambuttegama"},
// {value:"ANU16" , name:"Thalawa"},
// {value:"ANU17" , name:"Thirappane"},
// {value:"ANU18" , name:"Kekirawa"},
// {value:"ANU19" , name:"Palugaswewa"},
// {value:"ANU20" , name:"Ipalogama"},
// {value:"ANU21" , name:"Galnewa"},
// {value:"ANU22" , name:"Palagala"},
// {value:"POL0" , name:"Hingurakgoda"},
// {value:"POL1" , name:"Medirigiriya"},
// {value:"POL2" , name:"Lankapura"},
// {value:"POL3" , name:"Welikanda"},
// {value:"POL4" , name:"Welkanda"},
// {value:"POL5" , name:"Dimbulagala"},
// {value:"POL6" , name:"Thamankaduwa"},
// {value:"POL7" , name:"Elahera"},
// {value:"BAD0" , name:"Mahiyanganaya"},
// {value:"BAD1" , name:"Rideemaliyadda"},
// {value:"BAD2" , name:"Meegahakivula"},
// {value:"BAD3" , name:"Kandeketiya"},
// {value:"BAD4" , name:"Soranathota"},
// {value:"BAD5" , name:"Passara"},
// {value:"BAD6" , name:"Lunugala"},
// {value:"BAD7" , name:"Badulla"},
// {value:"BAD8" , name:"Hali Ela"},
// {value:"BAD9" , name:"Uva Paranagama"},
// {value:"BAD10" , name:"Welimada"},
// {value:"BAD11" , name:"Bandarawela"},
// {value:"BAD12" , name:"Ella"},
// {value:"BAD13" , name:"Haputale"},
// {value:"BAD14" , name:"Haputale "},
// {value:"BAD15" , name:"Haldummulla"},
// {value:"MON0" , name:"Bibile"},
// {value:"MON1" , name:"Madulla"},
// {value:"MON2" , name:"Medagama"},
// {value:"MON3" , name:"Siyambalanduwa"},
// {value:"MON4" , name:"Moneragala"},
// {value:"MON5" , name:"Badalkumbura"},
// {value:"MON6" , name:"Wellawaya"},
// {value:"MON7" , name:"Buttala"},
// {value:"MON8" , name:"Katharagama"},
// {value:"MON9" , name:"Thanamalvila"},
// {value:"MON10" , name:"Sevanagala"},
// {value:"RAT0" , name:"Eheliyagoda"},
// {value:"RAT1" , name:"Kuruvita"},
// {value:"RAT2" , name:"Kiriella"},
// {value:"RAT3" , name:"Kiiriella"},
// {value:"RAT4" , name:"Ratnapura"},
// {value:"RAT5" , name:"Imbulpe"},
// {value:"RAT6" , name:"Balangoda"},
// {value:"RAT7" , name:"Kalthota"},
// {value:"RAT8" , name:"Opanayaka"},
// {value:"RAT9" , name:"Pelmadulla"},
// {value:"RAT10" , name:"Elapatha"},
// {value:"RAT11" , name:"Ayagama"},
// {value:"RAT12" , name:"Kalawana"},
// {value:"RAT13" , name:"Nivitigala"},
// {value:"RAT14" , name:"Kahawatta"},
// {value:"RAT15" , name:"Godakawela"},
// {value:"RAT16" , name:"Weligepola"},
// {value:"RAT17" , name:"Embilipitiya"},
// {value:"RAT18" , name:"Kolonna"},
// {value:"KEG0" , name:"Rambukkana"},
// {value:"KEG1" , name:"Mawanella"},
// {value:"KEG2" , name:"Aranayaka"},
// {value:"KEG3" , name:"Kegalle"},
// {value:"KEG4" , name:"Galigamuwa"},
// {value:"KEG5" , name:"Warakapola"},
// {value:"KEG6" , name:"Ruwanwella"},
// {value:"KEG7" , name:"Bulathkohupitiya"},
// {value:"KEG8" , name:"Yatiyanthota"},
// {value:"KEG9" , name:"Dehiovita"},
// {value:"KEG10" , name:"Deraniyagala"},
// ];


// #TODO: this prolly should be in the constants folder
export const districts = [
    { discode:"COL" , district:"Colombo" },
    { discode:"GAM" , district:"Gampaha" },
    { discode:"KAL" , district:"Kalutara" },
    { discode:"KAN" , district:"Kandy" },
    { discode:"MAT" , district:"Matale" },
    { discode:"NUW" , district:"NuwaraEliya" }, //TODO: remember nuwara eliya is joined here
    { discode:"GAL" , district:"Galle" },
    { discode:"MTA" , district:"Matara" },
    { discode:"HAM" , district:"Hambantota" },
    { discode:"JAF" , district:"Jaffna" },
    { discode:"MAN" , district:"Mannar" },
    { discode:"VAV" , district:"Vavuniya" },
    { discode:"MUL" , district:"Mullaitivu" },
    { discode:"KIL" , district:"Kilinochchi" },
    { discode:"BAT" , district:"Batticaloa" },
    { discode:"AMP" , district:"Ampara" },
    { discode:"TRI" , district:"Trincomalee" },
    { discode:"KUR" , district:"Kurunegala" },
    { discode:"PUT" , district:"Puttalam" },
    { discode:"ANU" , district:"Anuradhapura" },
    { discode:"POL" , district:"Polonnaruwa" },
    { discode:"BAD" , district:"Badulla" },
    { discode:"MON" , district:"Moneragala" },
    { discode:"RAT" , district:"Rathnapura" },
    { discode:"KEG" , district:"Kegalle" },
];

// export const Colombo =
// [
// { divcode:"COL0" , division:"Colombo" },
// { divcode:"COL1" , division:"Kolonnawa" },
// { divcode:"COL2" , division:"Kaduwela" },
// { divcode:"COL3" , division:"Homagama" },
// { divcode:"COL4" , division:"Seethawaka" },
// { divcode:"COL5" , division:"Padukka" },
// { divcode:"COL6" , division:"Maharagama" },
// { divcode:"COL7" , division:"Sri Jayawardanapura Kotte" },
// { divcode:"COL8" , division:"Thimbirigasyaya" },
// { divcode:"COL9" , division:"Dehiwala" },
// { divcode:"COL10" , division:"Ratmalana" },
// { divcode:"COL11" , division:"Moratuwa" },
// { divcode:"COL12" , division:"Kesbewa" },
// ];
// export const Gampaha =
// [
// { divcode:"GAM0" , division:"Negombo" },
// { divcode:"GAM1" , division:"Katana" },
// { divcode:"GAM2" , division:"Divulapitiya" },
// { divcode:"GAM3" , division:"Mirigama" },
// { divcode:"GAM4" , division:"Minuwangoda" },
// { divcode:"GAM5" , division:"Wattala" },
// { divcode:"GAM6" , division:"Ja-Ela" },
// { divcode:"GAM7" , division:"Gampaha" },
// { divcode:"GAM8" , division:"Attanagalla" },
// { divcode:"GAM9" , division:"Dompe" },
// { divcode:"GAM10" , division:"Mahara" },
// { divcode:"GAM11" , division:"Kelaniya" },
// { divcode:"GAM12" , division:"Biyagama" },
// ];
// export const Kalutara =
// [
// { divcode:"KAL0" , division:"Panadura" },
// { divcode:"KAL1" , division:"Bandaragama" },
// { divcode:"KAL2" , division:"Horana" },
// { divcode:"KAL3" , division:"Ingiriya" },
// { divcode:"KAL4" , division:"Bulathsinhala" },
// { divcode:"KAL5" , division:"Madurawala" },
// { divcode:"KAL6" , division:"Millaniya" },
// { divcode:"KAL7" , division:"Kalutara" },
// { divcode:"KAL8" , division:"Beruwala" },
// { divcode:"KAL9" , division:"Dodangoda" },
// { divcode:"KAL10" , division:"Mathugama" },
// { divcode:"KAL11" , division:"Agalawatta" },
// { divcode:"KAL12" , division:"Palindanuwara" },
// { divcode:"KAL13" , division:"Walallawita" },
// ];
// export const Kandy =
// [
// { divcode:"KAN0" , division:"Thumpane" },
// { divcode:"KAN1" , division:"Pujapitiya" },
// { divcode:"KAN2" , division:"Akurana" },
// { divcode:"KAN3" , division:"Pathadumbara" },
// { divcode:"KAN4" , division:"Panvila" },
// { divcode:"KAN5" , division:"Udadumbara" },
// { divcode:"KAN6" , division:"Minipe" },
// { divcode:"KAN7" , division:"Medadumbara" },
// { divcode:"KAN8" , division:"Kundasale" },
// { divcode:"KAN9" , division:"Kandy Four Gravets & Gangawata Korale" },
// { divcode:"KAN10" , division:"Harispattuwa" },
// { divcode:"KAN11" , division:"Hatharaliyadda" },
// { divcode:"KAN12" , division:"Yatinuwara" },
// { divcode:"KAN13" , division:"Udunuwara" },
// { divcode:"KAN14" , division:"Doluwa" },
// { divcode:"KAN15" , division:"Pathahewaheta" },
// { divcode:"KAN16" , division:"Delthota" },
// { divcode:"KAN17" , division:"Udapalatha" },
// { divcode:"KAN18" , division:"Ganga Ihala Korale" },
// { divcode:"KAN19" , division:"Pasbage Korale" },
// ];
// export const Matale =
// [
// { divcode:"MAT0" , division:"Galewela" },
// { divcode:"MAT1" , division:"Dambulla" },
// { divcode:"MAT2" , division:"Naula" },
// { divcode:"MAT3" , division:"Pallepola" },
// { divcode:"MAT4" , division:"Yatawatta " },
// { divcode:"MAT5" , division:"Yatawatta" },
// { divcode:"MAT6" , division:"Matale" },
// { divcode:"MAT7" , division:"Ambanganga Korale" },
// { divcode:"MAT8" , division:"Laggala-Pallegama" },
// { divcode:"MAT9" , division:"Wilgamuwa" },
// { divcode:"MAT10" , division:"Rattota" },
// { divcode:"MAT11" , division:"Ukuwela" },
// ];
// export const NuwaraEliya =
// [
// { divcode:"NUW0" , division:"Kothmale" },
// { divcode:"NUW1" , division:"Hanguranketha" },
// { divcode:"NUW2" , division:"Walapane" },
// { divcode:"NUW3" , division:"Nuwara Eliya" },
// { divcode:"NUW4" , division:"Ambagamuwa" },
// ];
// export const Galle =
// [
// { divcode:"GAL0" , division:"Bentota" },
// { divcode:"GAL1" , division:"Balapitiya" },
// { divcode:"GAL2" , division:"Karandeniya" },
// { divcode:"GAL3" , division:"Elpitiya" },
// { divcode:"GAL4" , division:"Niyagama" },
// { divcode:"GAL5" , division:"Thawalama" },
// { divcode:"GAL6" , division:"Neluwa" },
// { divcode:"GAL7" , division:"Nagoda" },
// { divcode:"GAL8" , division:"Baddegama" },
// { divcode:"GAL9" , division:"Wanduramba" },
// { divcode:"GAL10" , division:"Welivitiya-Divithura" },
// { divcode:"GAL11" , division:"Ambalangoda" },
// { divcode:"GAL12" , division:"Gonapeenuwala" },
// { divcode:"GAL13" , division:"Madampagama" },
// { divcode:"GAL14" , division:"Hikkaduwa" },
// { divcode:"GAL15" , division:"Rathgama" },
// { divcode:"GAL16" , division:"Galle Four Gravets" },
// { divcode:"GAL17" , division:"Bope-Poddala" },
// { divcode:"GAL18" , division:"Akmeemana" },
// { divcode:"GAL19" , division:"Yakkalamulla" },
// { divcode:"GAL20" , division:"Imaduwa" },
// { divcode:"GAL21" , division:"Habaraduwa" },
// ];
// export const Matara =
// [
// { divcode:"MTA0" , division:"Pitabeddara" },
// { divcode:"MTA1" , division:"Kotapola" },
// { divcode:"MTA2" , division:"Pasgoda" },
// { divcode:"MTA3" , division:"Mulatiyana" },
// { divcode:"MTA4" , division:"Athuraliya" },
// { divcode:"MTA5" , division:"Akurassa" },
// { divcode:"MTA6" , division:"Welipitiya" },
// { divcode:"MTA7" , division:"Malimbada" },
// { divcode:"MTA8" , division:"Kamburupitiya" },
// { divcode:"MTA9" , division:"Hakmana" },
// { divcode:"MTA10" , division:"Kirinda -Puhulwella" },
// { divcode:"MTA11" , division:"Thihagoda" },
// { divcode:"MTA12" , division:"Weligama" },
// { divcode:"MTA13" , division:"Matara Four Gravets" },
// { divcode:"MTA14" , division:"Devinuwara" },
// { divcode:"MTA15" , division:"Dickwella" },
// ];
// export const Hambantota =
// [
// { divcode:"HAM0" , division:"Sooriyawewa" },
// { divcode:"HAM1" , division:"Lunugamvehera" },
// { divcode:"HAM2" , division:"Thissamaharama" },
// { divcode:"HAM3" , division:"Tissamaharamaya" },
// { divcode:"HAM4" , division:"Hambantota" },
// { divcode:"HAM5" , division:"Ambalantota" },
// { divcode:"HAM6" , division:"Angunakolapelessa" },
// { divcode:"HAM7" , division:"Weeraketiya" },
// { divcode:"HAM8" , division:"Katuwana" },
// { divcode:"HAM9" , division:"Walasmulla" },
// { divcode:"HAM10" , division:"Okewela" },
// { divcode:"HAM11" , division:"Beliatta" },
// { divcode:"HAM12" , division:"Tangalle" },
// ];
// export const Jaffna =
// [
// { divcode:"JAF0" , division:"Island North (Kayts)" },
// { divcode:"JAF1" , division:"Karainagar" },
// { divcode:"JAF2" , division:"Valikamam West" },
// { divcode:"JAF3" , division:"Valikamam South West (Sandilipay)" },
// { divcode:"JAF4" , division:"Valikamam North" },
// { divcode:"JAF5" , division:"Valikamam South (Uduvil)" },
// { divcode:"JAF6" , division:"Valikamam East (Kopay)" },
// { divcode:"JAF7" , division:"Vadamaradchi South-West (Karaveddy)" },
// { divcode:"JAF8" , division:"Vadamaradchy East" },
// { divcode:"JAF9" , division:"Vadamaradchi North (Point Pedro)" },
// { divcode:"JAF10" , division:"Thenmaradchi" },
// { divcode:"JAF11" , division:"Nallur" },
// { divcode:"JAF12" , division:"Jaffna" },
// { divcode:"JAF13" , division:"Island South (Velanai)" },
// { divcode:"JAF14" , division:"Delft" },
// ];
// export const Mannar =
// [
// { divcode:"MAN0" , division:"Mannar Town" },
// { divcode:"MAN1" , division:"Manthai West" },
// { divcode:"MAN2" , division:"Madhu" },
// { divcode:"MAN3" , division:"Nanattan" },
// { divcode:"MAN4" , division:"Musali" },
// ];
// export const Vavuniya =
// [
// { divcode:"VAV0" , division:"Vavuniya North" },
// { divcode:"VAV1" , division:"Vavuniya South" },
// { divcode:"VAV2" , division:"Vavuniya Town" },
// { divcode:"VAV3" , division:"Vengalacheddikulam" },
// ];
// export const Mullaitivu =
// [
// { divcode:"MUL0" , division:"Thunukkai" },
// { divcode:"MUL1" , division:"Manthai East" },
// { divcode:"MUL2" , division:"Puthukudiyiruppu" },
// { divcode:"MUL3" , division:"Oddusuddan" },
// { divcode:"MUL4" , division:"Meritimepattu" },
// { divcode:"MUL5" , division:"Welioya" },
// ];
// export const Kilinochchi =
// [
// { divcode:"KIL0" , division:"Pachchilaipalli" },
// { divcode:"KIL1" , division:"Kandawalai" },
// { divcode:"KIL2" , division:"Karachchi" },
// { divcode:"KIL3" , division:"Poonakary" },
// ];
// export const Batticaloa =
// [
// { divcode:"BAT0" , division:"Koralai Pattu North (Vaharai)" },
// { divcode:"BAT1" , division:"Koralai Pattu Central" },
// { divcode:"BAT2" , division:"Koralaipattu West (Oddamavadi)" },
// { divcode:"BAT3" , division:"Koralai Pattu(Valachchenai)" },
// { divcode:"BAT4" , division:"Koralai Pattu South (Kiran)" },
// { divcode:"BAT5" , division:"Eravur Pattu" },
// { divcode:"BAT6" , division:"Eravur Town" },
// { divcode:"BAT7" , division:"Manmunai North" },
// { divcode:"BAT8" , division:"Manmunai West" },
// { divcode:"BAT9" , division:"Kattankudy" },
// { divcode:"BAT10" , division:"Manmunai Pattu(Araipattai)" },
// { divcode:"BAT11" , division:"Manmunai South-West" },
// { divcode:"BAT12" , division:"Poratheevu Pattu" },
// { divcode:"BAT13" , division:"Pratheevu Pattu" },
// { divcode:"BAT14" , division:"Manmunai South & Eruvil pattu" },
// ];
// export const Ampara =
// [
// { divcode:"AMP0" , division:"Dehiattakandiya" },
// { divcode:"AMP1" , division:"Padiyathalawa" },
// { divcode:"AMP2" , division:"Mahaoya" },
// { divcode:"AMP3" , division:"Uhana" },
// { divcode:"AMP4" , division:"Ampara" },
// { divcode:"AMP5" , division:"Navithanveli" },
// { divcode:"AMP6" , division:"Sammanthurai" },
// { divcode:"AMP7" , division:"Kalmunai Tamil Division" },
// { divcode:"AMP8" , division:"Kalmunai" },
// { divcode:"AMP9" , division:"Sainthamaruthu" },
// { divcode:"AMP10" , division:"Karaitheevu" },
// { divcode:"AMP11" , division:"Ninthavur" },
// { divcode:"AMP12" , division:"Addalachchenai" },
// { divcode:"AMP13" , division:"Irakkamam" },
// { divcode:"AMP14" , division:"Akkaraipattu" },
// { divcode:"AMP15" , division:"Akkaraipattu " },
// { divcode:"AMP16" , division:"Alayadiwembu" },
// { divcode:"AMP17" , division:"Damana" },
// { divcode:"AMP18" , division:"Thirukkovil" },
// { divcode:"AMP19" , division:"Pottuvil" },
// { divcode:"AMP20" , division:"Lahugala" },
// ];
// export const Trincomalee =
// [
// { divcode:"TRI0" , division:"Padavisiripura" },
// { divcode:"TRI1" , division:"Kuchchaveli" },
// { divcode:"TRI2" , division:"Gomarankadawala" },
// { divcode:"TRI3" , division:"Morawewa" },
// { divcode:"TRI4" , division:"Trincomalee Town and Gravets" },
// { divcode:"TRI5" , division:"Thambalagamuwa" },
// { divcode:"TRI6" , division:"Kanthale" },
// { divcode:"TRI7" , division:"Kinniya" },
// { divcode:"TRI8" , division:"Muttur" },
// { divcode:"TRI9" , division:"Seruvila" },
// { divcode:"TRI10" , division:"Verugal(Eachchilampattu)" },
// ];
// export const Kurunegala =
// [
// { divcode:"KUR0" , division:"Giribawa" },
// { divcode:"KUR1" , division:"Galgamuwa" },
// { divcode:"KUR2" , division:"Ehetuwewa" },
// { divcode:"KUR3" , division:"Ambanpola" },
// { divcode:"KUR4" , division:"Kotavehera" },
// { divcode:"KUR5" , division:"Rasnayakapura" },
// { divcode:"KUR6" , division:"Nikaweratiya" },
// { divcode:"KUR7" , division:"Maho" },
// { divcode:"KUR8" , division:"Polpithigama" },
// { divcode:"KUR9" , division:"Ibbagamuwa" },
// { divcode:"KUR10" , division:"Ganewatta" },
// { divcode:"KUR11" , division:"Wariyapola" },
// { divcode:"KUR12" , division:"Kobeigane" },
// { divcode:"KUR13" , division:"Bingiriya" },
// { divcode:"KUR14" , division:"Panduwasnuwara West" },
// { divcode:"KUR15" , division:"Panduwasnuwara East" },
// { divcode:"KUR16" , division:"Bamunakotuwa" },
// { divcode:"KUR17" , division:"Maspotha" },
// { divcode:"KUR18" , division:"Kurunegala" },
// { divcode:"KUR19" , division:"Mallawapitiya" },
// { divcode:"KUR20" , division:"Mawathagama" },
// { divcode:"KUR21" , division:"Mawathagama " },
// { divcode:"KUR22" , division:"Rideegama" },
// { divcode:"KUR23" , division:"Weerambugedara" },
// { divcode:"KUR24" , division:"Kuliyapitiya East" },
// { divcode:"KUR25" , division:"Kuliyapitiya West" },
// { divcode:"KUR26" , division:"Udubaddawa" },
// { divcode:"KUR27" , division:"Pannala" },
// { divcode:"KUR28" , division:"Narammala" },
// { divcode:"KUR29" , division:"Alawwa" },
// { divcode:"KUR30" , division:"Polgahawela" },
// ];
// export const Puttalam =
// [
// { divcode:"PUT0" , division:"Kalpitiya" },
// { divcode:"PUT1" , division:"Vanathawilluwa" },
// { divcode:"PUT2" , division:"Karuwalagaswewa" },
// { divcode:"PUT3" , division:"Nawagattegama" },
// { divcode:"PUT4" , division:"Puttalam" },
// { divcode:"PUT5" , division:"Mundel" },
// { divcode:"PUT6" , division:"Mahakumbukkadawala" },
// { divcode:"PUT7" , division:"Anamaduwa" },
// { divcode:"PUT8" , division:"Pallama" },
// { divcode:"PUT9" , division:"Arachchikattuwa" },
// { divcode:"PUT10" , division:"Chilaw" },
// { divcode:"PUT11" , division:"Madampe" },
// { divcode:"PUT12" , division:"Mahawewa" },
// { divcode:"PUT13" , division:"Nattandiya" },
// { divcode:"PUT14" , division:"Wennappuwa" },
// { divcode:"PUT15" , division:"Dankotuwa" },
// ];
// export const Anuradhapura =
// [
// { divcode:"ANU0" , division:"Padaviya" },
// { divcode:"ANU1" , division:"Kebithigollewa" },
// { divcode:"ANU2" , division:"Madawachchiya" },
// { divcode:"ANU3" , division:"Medawachchiya" },
// { divcode:"ANU4" , division:"Mahawilachchiya" },
// { divcode:"ANU5" , division:"Nuwaragam Palatha Central" },
// { divcode:"ANU6" , division:"Rambewa" },
// { divcode:"ANU7" , division:"Kahatagasdigiliya" },
// { divcode:"ANU8" , division:"Horowpothana" },
// { divcode:"ANU9" , division:"Galenbindunuwewa" },
// { divcode:"ANU10" , division:"Mihinthale" },
// { divcode:"ANU11" , division:"Nuwaragam Palatha East" },
// { divcode:"ANU12" , division:"Nachchadoowa" },
// { divcode:"ANU13" , division:"Nochchiyagama" },
// { divcode:"ANU14" , division:"Rajanganaya" },
// { divcode:"ANU15" , division:"Thambuttegama" },
// { divcode:"ANU16" , division:"Thalawa" },
// { divcode:"ANU17" , division:"Thirappane" },
// { divcode:"ANU18" , division:"Kekirawa" },
// { divcode:"ANU19" , division:"Palugaswewa" },
// { divcode:"ANU20" , division:"Ipalogama" },
// { divcode:"ANU21" , division:"Galnewa" },
// { divcode:"ANU22" , division:"Palagala" },
// ];
// export const Polonnaruwa =
// [
// { divcode:"POL0" , division:"Hingurakgoda" },
// { divcode:"POL1" , division:"Medirigiriya" },
// { divcode:"POL2" , division:"Lankapura" },
// { divcode:"POL3" , division:"Welikanda" },
// { divcode:"POL4" , division:"Welkanda" },
// { divcode:"POL5" , division:"Dimbulagala" },
// { divcode:"POL6" , division:"Thamankaduwa" },
// { divcode:"POL7" , division:"Elahera" },
// ];
// export const Badulla =
// [
// { divcode:"BAD0" , division:"Mahiyanganaya" },
// { divcode:"BAD1" , division:"Rideemaliyadda" },
// { divcode:"BAD2" , division:"Meegahakivula" },
// { divcode:"BAD3" , division:"Kandeketiya" },
// { divcode:"BAD4" , division:"Soranathota" },
// { divcode:"BAD5" , division:"Passara" },
// { divcode:"BAD6" , division:"Lunugala" },
// { divcode:"BAD7" , division:"Badulla" },
// { divcode:"BAD8" , division:"Hali Ela" },
// { divcode:"BAD9" , division:"Uva Paranagama" },
// { divcode:"BAD10" , division:"Welimada" },
// { divcode:"BAD11" , division:"Bandarawela" },
// { divcode:"BAD12" , division:"Ella" },
// { divcode:"BAD13" , division:"Haputale" },
// { divcode:"BAD14" , division:"Haputale " },
// { divcode:"BAD15" , division:"Haldummulla" },
// ];
// export const Moneragala =
// [
// { divcode:"MON0" , division:"Bibile" },
// { divcode:"MON1" , division:"Madulla" },
// { divcode:"MON2" , division:"Medagama" },
// { divcode:"MON3" , division:"Siyambalanduwa" },
// { divcode:"MON4" , division:"Moneragala" },
// { divcode:"MON5" , division:"Badalkumbura" },
// { divcode:"MON6" , division:"Wellawaya" },
// { divcode:"MON7" , division:"Buttala" },
// { divcode:"MON8" , division:"Katharagama" },
// { divcode:"MON9" , division:"Thanamalvila" },
// { divcode:"MON10" , division:"Sevanagala" },
// ];
// export const Rathnapura =
// [
// { divcode:"RAT0" , division:"Eheliyagoda" },
// { divcode:"RAT1" , division:"Kuruvita" },
// { divcode:"RAT2" , division:"Kiriella" },
// { divcode:"RAT3" , division:"Kiiriella" },
// { divcode:"RAT4" , division:"Ratnapura" },
// { divcode:"RAT5" , division:"Imbulpe" },
// { divcode:"RAT6" , division:"Balangoda" },
// { divcode:"RAT7" , division:"Kalthota" },
// { divcode:"RAT8" , division:"Opanayaka" },
// { divcode:"RAT9" , division:"Pelmadulla" },
// { divcode:"RAT10" , division:"Elapatha" },
// { divcode:"RAT11" , division:"Ayagama" },
// { divcode:"RAT12" , division:"Kalawana" },
// { divcode:"RAT13" , division:"Nivitigala" },
// { divcode:"RAT14" , division:"Kahawatta" },
// { divcode:"RAT15" , division:"Godakawela" },
// { divcode:"RAT16" , division:"Weligepola" },
// { divcode:"RAT17" , division:"Embilipitiya" },
// { divcode:"RAT18" , division:"Kolonna" },
// ];
// export const Kegalle =
// [
// { divcode:"KEG0" , division:"Rambukkana" },
// { divcode:"KEG1" , division:"Mawanella" },
// { divcode:"KEG2" , division:"Aranayaka" },
// { divcode:"KEG3" , division:"Kegalle" },
// { divcode:"KEG4" , division:"Galigamuwa" },
// { divcode:"KEG5" , division:"Warakapola" },
// { divcode:"KEG6" , division:"Ruwanwella" },
// { divcode:"KEG7" , division:"Bulathkohupitiya" },
// { divcode:"KEG8" , division:"Yatiyanthota" },
// { divcode:"KEG9" , division:"Dehiovita" },
// { divcode:"KEG10" , division:"Deraniyagala" },
// ];

type Division = {
    divcode: string;
    division: string;
  };
  
  type LocationsType = {
    [key: string]: Division[];
  };

export const LOCATIONS:LocationsType = 
{
    Colombo :
    [
    { divcode:"COL0" , division:"Colombo" },
    { divcode:"COL1" , division:"Kolonnawa" },
    { divcode:"COL2" , division:"Kaduwela" },
    { divcode:"COL3" , division:"Homagama" },
    { divcode:"COL4" , division:"Seethawaka" },
    { divcode:"COL5" , division:"Padukka" },
    { divcode:"COL6" , division:"Maharagama" },
    { divcode:"COL7" , division:"Sri Jayawardanapura Kotte" },
    { divcode:"COL8" , division:"Thimbirigasyaya" },
    { divcode:"COL9" , division:"Dehiwala" },
    { divcode:"COL10" , division:"Ratmalana" },
    { divcode:"COL11" , division:"Moratuwa" },
    { divcode:"COL12" , division:"Kesbewa" },
    ],
    Gampaha :
    [
    { divcode:"GAM0" , division:"Negombo" },
    { divcode:"GAM1" , division:"Katana" },
    { divcode:"GAM2" , division:"Divulapitiya" },
    { divcode:"GAM3" , division:"Mirigama" },
    { divcode:"GAM4" , division:"Minuwangoda" },
    { divcode:"GAM5" , division:"Wattala" },
    { divcode:"GAM6" , division:"Ja-Ela" },
    { divcode:"GAM7" , division:"Gampaha" },
    { divcode:"GAM8" , division:"Attanagalla" },
    { divcode:"GAM9" , division:"Dompe" },
    { divcode:"GAM10" , division:"Mahara" },
    { divcode:"GAM11" , division:"Kelaniya" },
    { divcode:"GAM12" , division:"Biyagama" },
    ],
    Kalutara :
    [
    { divcode:"KAL0" , division:"Panadura" },
    { divcode:"KAL1" , division:"Bandaragama" },
    { divcode:"KAL2" , division:"Horana" },
    { divcode:"KAL3" , division:"Ingiriya" },
    { divcode:"KAL4" , division:"Bulathsinhala" },
    { divcode:"KAL5" , division:"Madurawala" },
    { divcode:"KAL6" , division:"Millaniya" },
    { divcode:"KAL7" , division:"Kalutara" },
    { divcode:"KAL8" , division:"Beruwala" },
    { divcode:"KAL9" , division:"Dodangoda" },
    { divcode:"KAL10" , division:"Mathugama" },
    { divcode:"KAL11" , division:"Agalawatta" },
    { divcode:"KAL12" , division:"Palindanuwara" },
    { divcode:"KAL13" , division:"Walallawita" },
    ],
    Kandy :
    [
    { divcode:"KAN0" , division:"Thumpane" },
    { divcode:"KAN1" , division:"Pujapitiya" },
    { divcode:"KAN2" , division:"Akurana" },
    { divcode:"KAN3" , division:"Pathadumbara" },
    { divcode:"KAN4" , division:"Panvila" },
    { divcode:"KAN5" , division:"Udadumbara" },
    { divcode:"KAN6" , division:"Minipe" },
    { divcode:"KAN7" , division:"Medadumbara" },
    { divcode:"KAN8" , division:"Kundasale" },
    { divcode:"KAN9" , division:"Kandy Four Gravets & Gangawata Korale" },
    { divcode:"KAN10" , division:"Harispattuwa" },
    { divcode:"KAN11" , division:"Hatharaliyadda" },
    { divcode:"KAN12" , division:"Yatinuwara" },
    { divcode:"KAN13" , division:"Udunuwara" },
    { divcode:"KAN14" , division:"Doluwa" },
    { divcode:"KAN15" , division:"Pathahewaheta" },
    { divcode:"KAN16" , division:"Delthota" },
    { divcode:"KAN17" , division:"Udapalatha" },
    { divcode:"KAN18" , division:"Ganga Ihala Korale" },
    { divcode:"KAN19" , division:"Pasbage Korale" },
    ],
    Matale :
    [
    { divcode:"MAT0" , division:"Galewela" },
    { divcode:"MAT1" , division:"Dambulla" },
    { divcode:"MAT2" , division:"Naula" },
    { divcode:"MAT3" , division:"Pallepola" },
    { divcode:"MAT4" , division:"Yatawatta " },
    { divcode:"MAT5" , division:"Yatawatta" },
    { divcode:"MAT6" , division:"Matale" },
    { divcode:"MAT7" , division:"Ambanganga Korale" },
    { divcode:"MAT8" , division:"Laggala-Pallegama" },
    { divcode:"MAT9" , division:"Wilgamuwa" },
    { divcode:"MAT10" , division:"Rattota" },
    { divcode:"MAT11" , division:"Ukuwela" },
    ],
    NuwaraEliya :
    [
    { divcode:"NUW0" , division:"Kothmale" },
    { divcode:"NUW1" , division:"Hanguranketha" },
    { divcode:"NUW2" , division:"Walapane" },
    { divcode:"NUW3" , division:"Nuwara Eliya" },
    { divcode:"NUW4" , division:"Ambagamuwa" },
    ],
    Galle :
    [
    { divcode:"GAL0" , division:"Bentota" },
    { divcode:"GAL1" , division:"Balapitiya" },
    { divcode:"GAL2" , division:"Karandeniya" },
    { divcode:"GAL3" , division:"Elpitiya" },
    { divcode:"GAL4" , division:"Niyagama" },
    { divcode:"GAL5" , division:"Thawalama" },
    { divcode:"GAL6" , division:"Neluwa" },
    { divcode:"GAL7" , division:"Nagoda" },
    { divcode:"GAL8" , division:"Baddegama" },
    { divcode:"GAL9" , division:"Wanduramba" },
    { divcode:"GAL10" , division:"Welivitiya-Divithura" },
    { divcode:"GAL11" , division:"Ambalangoda" },
    { divcode:"GAL12" , division:"Gonapeenuwala" },
    { divcode:"GAL13" , division:"Madampagama" },
    { divcode:"GAL14" , division:"Hikkaduwa" },
    { divcode:"GAL15" , division:"Rathgama" },
    { divcode:"GAL16" , division:"Galle Four Gravets" },
    { divcode:"GAL17" , division:"Bope-Poddala" },
    { divcode:"GAL18" , division:"Akmeemana" },
    { divcode:"GAL19" , division:"Yakkalamulla" },
    { divcode:"GAL20" , division:"Imaduwa" },
    { divcode:"GAL21" , division:"Habaraduwa" },
    ],
    Matara :
    [
    { divcode:"MTA0" , division:"Pitabeddara" },
    { divcode:"MTA1" , division:"Kotapola" },
    { divcode:"MTA2" , division:"Pasgoda" },
    { divcode:"MTA3" , division:"Mulatiyana" },
    { divcode:"MTA4" , division:"Athuraliya" },
    { divcode:"MTA5" , division:"Akurassa" },
    { divcode:"MTA6" , division:"Welipitiya" },
    { divcode:"MTA7" , division:"Malimbada" },
    { divcode:"MTA8" , division:"Kamburupitiya" },
    { divcode:"MTA9" , division:"Hakmana" },
    { divcode:"MTA10" , division:"Kirinda -Puhulwella" },
    { divcode:"MTA11" , division:"Thihagoda" },
    { divcode:"MTA12" , division:"Weligama" },
    { divcode:"MTA13" , division:"Matara Four Gravets" },
    { divcode:"MTA14" , division:"Devinuwara" },
    { divcode:"MTA15" , division:"Dickwella" },
    ],
    Hambantota :
    [
    { divcode:"HAM0" , division:"Sooriyawewa" },
    { divcode:"HAM1" , division:"Lunugamvehera" },
    { divcode:"HAM2" , division:"Thissamaharama" },
    { divcode:"HAM3" , division:"Tissamaharamaya" },
    { divcode:"HAM4" , division:"Hambantota" },
    { divcode:"HAM5" , division:"Ambalantota" },
    { divcode:"HAM6" , division:"Angunakolapelessa" },
    { divcode:"HAM7" , division:"Weeraketiya" },
    { divcode:"HAM8" , division:"Katuwana" },
    { divcode:"HAM9" , division:"Walasmulla" },
    { divcode:"HAM10" , division:"Okewela" },
    { divcode:"HAM11" , division:"Beliatta" },
    { divcode:"HAM12" , division:"Tangalle" },
    ],
    Jaffna :
    [
    { divcode:"JAF0" , division:"Island North (Kayts)" },
    { divcode:"JAF1" , division:"Karainagar" },
    { divcode:"JAF2" , division:"Valikamam West" },
    { divcode:"JAF3" , division:"Valikamam South West (Sandilipay)" },
    { divcode:"JAF4" , division:"Valikamam North" },
    { divcode:"JAF5" , division:"Valikamam South (Uduvil)" },
    { divcode:"JAF6" , division:"Valikamam East (Kopay)" },
    { divcode:"JAF7" , division:"Vadamaradchi South-West (Karaveddy)" },
    { divcode:"JAF8" , division:"Vadamaradchy East" },
    { divcode:"JAF9" , division:"Vadamaradchi North (Point Pedro)" },
    { divcode:"JAF10" , division:"Thenmaradchi" },
    { divcode:"JAF11" , division:"Nallur" },
    { divcode:"JAF12" , division:"Jaffna" },
    { divcode:"JAF13" , division:"Island South (Velanai)" },
    { divcode:"JAF14" , division:"Delft" },
    ],
    Mannar :
    [
    { divcode:"MAN0" , division:"Mannar Town" },
    { divcode:"MAN1" , division:"Manthai West" },
    { divcode:"MAN2" , division:"Madhu" },
    { divcode:"MAN3" , division:"Nanattan" },
    { divcode:"MAN4" , division:"Musali" },
    ],
    Vavuniya :
    [
    { divcode:"VAV0" , division:"Vavuniya North" },
    { divcode:"VAV1" , division:"Vavuniya South" },
    { divcode:"VAV2" , division:"Vavuniya Town" },
    { divcode:"VAV3" , division:"Vengalacheddikulam" },
    ],
    Mullaitivu :
    [
    { divcode:"MUL0" , division:"Thunukkai" },
    { divcode:"MUL1" , division:"Manthai East" },
    { divcode:"MUL2" , division:"Puthukudiyiruppu" },
    { divcode:"MUL3" , division:"Oddusuddan" },
    { divcode:"MUL4" , division:"Meritimepattu" },
    { divcode:"MUL5" , division:"Welioya" },
    ],
    Kilinochchi :
    [
    { divcode:"KIL0" , division:"Pachchilaipalli" },
    { divcode:"KIL1" , division:"Kandawalai" },
    { divcode:"KIL2" , division:"Karachchi" },
    { divcode:"KIL3" , division:"Poonakary" },
    ],
    Batticaloa :
    [
    { divcode:"BAT0" , division:"Koralai Pattu North (Vaharai)" },
    { divcode:"BAT1" , division:"Koralai Pattu Central" },
    { divcode:"BAT2" , division:"Koralaipattu West (Oddamavadi)" },
    { divcode:"BAT3" , division:"Koralai Pattu(Valachchenai)" },
    { divcode:"BAT4" , division:"Koralai Pattu South (Kiran)" },
    { divcode:"BAT5" , division:"Eravur Pattu" },
    { divcode:"BAT6" , division:"Eravur Town" },
    { divcode:"BAT7" , division:"Manmunai North" },
    { divcode:"BAT8" , division:"Manmunai West" },
    { divcode:"BAT9" , division:"Kattankudy" },
    { divcode:"BAT10" , division:"Manmunai Pattu(Araipattai)" },
    { divcode:"BAT11" , division:"Manmunai South-West" },
    { divcode:"BAT12" , division:"Poratheevu Pattu" },
    { divcode:"BAT13" , division:"Pratheevu Pattu" },
    { divcode:"BAT14" , division:"Manmunai South & Eruvil pattu" },
    ],
    Ampara :
    [
    { divcode:"AMP0" , division:"Dehiattakandiya" },
    { divcode:"AMP1" , division:"Padiyathalawa" },
    { divcode:"AMP2" , division:"Mahaoya" },
    { divcode:"AMP3" , division:"Uhana" },
    { divcode:"AMP4" , division:"Ampara" },
    { divcode:"AMP5" , division:"Navithanveli" },
    { divcode:"AMP6" , division:"Sammanthurai" },
    { divcode:"AMP7" , division:"Kalmunai Tamil Division" },
    { divcode:"AMP8" , division:"Kalmunai" },
    { divcode:"AMP9" , division:"Sainthamaruthu" },
    { divcode:"AMP10" , division:"Karaitheevu" },
    { divcode:"AMP11" , division:"Ninthavur" },
    { divcode:"AMP12" , division:"Addalachchenai" },
    { divcode:"AMP13" , division:"Irakkamam" },
    { divcode:"AMP14" , division:"Akkaraipattu" },
    { divcode:"AMP15" , division:"Akkaraipattu " },
    { divcode:"AMP16" , division:"Alayadiwembu" },
    { divcode:"AMP17" , division:"Damana" },
    { divcode:"AMP18" , division:"Thirukkovil" },
    { divcode:"AMP19" , division:"Pottuvil" },
    { divcode:"AMP20" , division:"Lahugala" },
    ],
    Trincomalee :
    [
    { divcode:"TRI0" , division:"Padavisiripura" },
    { divcode:"TRI1" , division:"Kuchchaveli" },
    { divcode:"TRI2" , division:"Gomarankadawala" },
    { divcode:"TRI3" , division:"Morawewa" },
    { divcode:"TRI4" , division:"Trincomalee Town and Gravets" },
    { divcode:"TRI5" , division:"Thambalagamuwa" },
    { divcode:"TRI6" , division:"Kanthale" },
    { divcode:"TRI7" , division:"Kinniya" },
    { divcode:"TRI8" , division:"Muttur" },
    { divcode:"TRI9" , division:"Seruvila" },
    { divcode:"TRI10" , division:"Verugal(Eachchilampattu)" },
    ],
    Kurunegala :
    [
    { divcode:"KUR0" , division:"Giribawa" },
    { divcode:"KUR1" , division:"Galgamuwa" },
    { divcode:"KUR2" , division:"Ehetuwewa" },
    { divcode:"KUR3" , division:"Ambanpola" },
    { divcode:"KUR4" , division:"Kotavehera" },
    { divcode:"KUR5" , division:"Rasnayakapura" },
    { divcode:"KUR6" , division:"Nikaweratiya" },
    { divcode:"KUR7" , division:"Maho" },
    { divcode:"KUR8" , division:"Polpithigama" },
    { divcode:"KUR9" , division:"Ibbagamuwa" },
    { divcode:"KUR10" , division:"Ganewatta" },
    { divcode:"KUR11" , division:"Wariyapola" },
    { divcode:"KUR12" , division:"Kobeigane" },
    { divcode:"KUR13" , division:"Bingiriya" },
    { divcode:"KUR14" , division:"Panduwasnuwara West" },
    { divcode:"KUR15" , division:"Panduwasnuwara East" },
    { divcode:"KUR16" , division:"Bamunakotuwa" },
    { divcode:"KUR17" , division:"Maspotha" },
    { divcode:"KUR18" , division:"Kurunegala" },
    { divcode:"KUR19" , division:"Mallawapitiya" },
    { divcode:"KUR20" , division:"Mawathagama" },
    { divcode:"KUR21" , division:"Mawathagama " },
    { divcode:"KUR22" , division:"Rideegama" },
    { divcode:"KUR23" , division:"Weerambugedara" },
    { divcode:"KUR24" , division:"Kuliyapitiya East" },
    { divcode:"KUR25" , division:"Kuliyapitiya West" },
    { divcode:"KUR26" , division:"Udubaddawa" },
    { divcode:"KUR27" , division:"Pannala" },
    { divcode:"KUR28" , division:"Narammala" },
    { divcode:"KUR29" , division:"Alawwa" },
    { divcode:"KUR30" , division:"Polgahawela" },
    ],
    Puttalam :
    [
    { divcode:"PUT0" , division:"Kalpitiya" },
    { divcode:"PUT1" , division:"Vanathawilluwa" },
    { divcode:"PUT2" , division:"Karuwalagaswewa" },
    { divcode:"PUT3" , division:"Nawagattegama" },
    { divcode:"PUT4" , division:"Puttalam" },
    { divcode:"PUT5" , division:"Mundel" },
    { divcode:"PUT6" , division:"Mahakumbukkadawala" },
    { divcode:"PUT7" , division:"Anamaduwa" },
    { divcode:"PUT8" , division:"Pallama" },
    { divcode:"PUT9" , division:"Arachchikattuwa" },
    { divcode:"PUT10" , division:"Chilaw" },
    { divcode:"PUT11" , division:"Madampe" },
    { divcode:"PUT12" , division:"Mahawewa" },
    { divcode:"PUT13" , division:"Nattandiya" },
    { divcode:"PUT14" , division:"Wennappuwa" },
    { divcode:"PUT15" , division:"Dankotuwa" },
    ],
    Anuradhapura :
    [
    { divcode:"ANU0" , division:"Padaviya" },
    { divcode:"ANU1" , division:"Kebithigollewa" },
    { divcode:"ANU2" , division:"Madawachchiya" },
    { divcode:"ANU3" , division:"Medawachchiya" },
    { divcode:"ANU4" , division:"Mahawilachchiya" },
    { divcode:"ANU5" , division:"Nuwaragam Palatha Central" },
    { divcode:"ANU6" , division:"Rambewa" },
    { divcode:"ANU7" , division:"Kahatagasdigiliya" },
    { divcode:"ANU8" , division:"Horowpothana" },
    { divcode:"ANU9" , division:"Galenbindunuwewa" },
    { divcode:"ANU10" , division:"Mihinthale" },
    { divcode:"ANU11" , division:"Nuwaragam Palatha East" },
    { divcode:"ANU12" , division:"Nachchadoowa" },
    { divcode:"ANU13" , division:"Nochchiyagama" },
    { divcode:"ANU14" , division:"Rajanganaya" },
    { divcode:"ANU15" , division:"Thambuttegama" },
    { divcode:"ANU16" , division:"Thalawa" },
    { divcode:"ANU17" , division:"Thirappane" },
    { divcode:"ANU18" , division:"Kekirawa" },
    { divcode:"ANU19" , division:"Palugaswewa" },
    { divcode:"ANU20" , division:"Ipalogama" },
    { divcode:"ANU21" , division:"Galnewa" },
    { divcode:"ANU22" , division:"Palagala" },
    ],
    Polonnaruwa :
    [
    { divcode:"POL0" , division:"Hingurakgoda" },
    { divcode:"POL1" , division:"Medirigiriya" },
    { divcode:"POL2" , division:"Lankapura" },
    { divcode:"POL3" , division:"Welikanda" },
    { divcode:"POL4" , division:"Welkanda" },
    { divcode:"POL5" , division:"Dimbulagala" },
    { divcode:"POL6" , division:"Thamankaduwa" },
    { divcode:"POL7" , division:"Elahera" },
    ],
    Badulla :
    [
    { divcode:"BAD0" , division:"Mahiyanganaya" },
    { divcode:"BAD1" , division:"Rideemaliyadda" },
    { divcode:"BAD2" , division:"Meegahakivula" },
    { divcode:"BAD3" , division:"Kandeketiya" },
    { divcode:"BAD4" , division:"Soranathota" },
    { divcode:"BAD5" , division:"Passara" },
    { divcode:"BAD6" , division:"Lunugala" },
    { divcode:"BAD7" , division:"Badulla" },
    { divcode:"BAD8" , division:"Hali Ela" },
    { divcode:"BAD9" , division:"Uva Paranagama" },
    { divcode:"BAD10" , division:"Welimada" },
    { divcode:"BAD11" , division:"Bandarawela" },
    { divcode:"BAD12" , division:"Ella" },
    { divcode:"BAD13" , division:"Haputale" },
    { divcode:"BAD14" , division:"Haputale " },
    { divcode:"BAD15" , division:"Haldummulla" },
    ],
    Moneragala :
    [
    { divcode:"MON0" , division:"Bibile" },
    { divcode:"MON1" , division:"Madulla" },
    { divcode:"MON2" , division:"Medagama" },
    { divcode:"MON3" , division:"Siyambalanduwa" },
    { divcode:"MON4" , division:"Moneragala" },
    { divcode:"MON5" , division:"Badalkumbura" },
    { divcode:"MON6" , division:"Wellawaya" },
    { divcode:"MON7" , division:"Buttala" },
    { divcode:"MON8" , division:"Katharagama" },
    { divcode:"MON9" , division:"Thanamalvila" },
    { divcode:"MON10" , division:"Sevanagala" },
    ],
    Rathnapura :
    [
    { divcode:"RAT0" , division:"Eheliyagoda" },
    { divcode:"RAT1" , division:"Kuruvita" },
    { divcode:"RAT2" , division:"Kiriella" },
    { divcode:"RAT3" , division:"Kiiriella" },
    { divcode:"RAT4" , division:"Ratnapura" },
    { divcode:"RAT5" , division:"Imbulpe" },
    { divcode:"RAT6" , division:"Balangoda" },
    { divcode:"RAT7" , division:"Kalthota" },
    { divcode:"RAT8" , division:"Opanayaka" },
    { divcode:"RAT9" , division:"Pelmadulla" },
    { divcode:"RAT10" , division:"Elapatha" },
    { divcode:"RAT11" , division:"Ayagama" },
    { divcode:"RAT12" , division:"Kalawana" },
    { divcode:"RAT13" , division:"Nivitigala" },
    { divcode:"RAT14" , division:"Kahawatta" },
    { divcode:"RAT15" , division:"Godakawela" },
    { divcode:"RAT16" , division:"Weligepola" },
    { divcode:"RAT17" , division:"Embilipitiya" },
    { divcode:"RAT18" , division:"Kolonna" },
    ],
    Kegalle :
    [
    { divcode:"KEG0" , division:"Rambukkana" },
    { divcode:"KEG1" , division:"Mawanella" },
    { divcode:"KEG2" , division:"Aranayaka" },
    { divcode:"KEG3" , division:"Kegalle" },
    { divcode:"KEG4" , division:"Galigamuwa" },
    { divcode:"KEG5" , division:"Warakapola" },
    { divcode:"KEG6" , division:"Ruwanwella" },
    { divcode:"KEG7" , division:"Bulathkohupitiya" },
    { divcode:"KEG8" , division:"Yatiyanthota" },
    { divcode:"KEG9" , division:"Dehiovita" },
    { divcode:"KEG10" , division:"Deraniyagala" },
    ],
    }