import { ComboboxData } from "@mantine/core";
// type Division = {
//     value: string;
//     label: string;
//   };

type LocationsType = {
    [key: string]: ComboboxData;
};



// #TODO: this prolly should be in the constants folder
export const districts = [
    { discode:"COL" , district:"Colombo" },
    { discode:"GAM" , district:"Gampaha" },
    { discode:"KAL" , district:"Kalutara" },
    { discode:"KAN" , district:"Kandy" },
    { discode:"MAT" , district:"Matale" },
    { discode:"NUW" , district:"NuwaraEliya" }, //TODO: remember nuwara eliya is joined here
    { discode:"GAL" , district:"Galle" },
    { discode:"MTA" , district:"Matara" },
    { discode:"HAM" , district:"Hambantota" },
    { discode:"JAF" , district:"Jaffna" },
    { discode:"MAN" , district:"Mannar" },
    { discode:"VAV" , district:"Vavuniya" },
    { discode:"MUL" , district:"Mullaitivu" },
    { discode:"KIL" , district:"Kilinochchi" },
    { discode:"BAT" , district:"Batticaloa" },
    { discode:"AMP" , district:"Ampara" },
    { discode:"TRI" , district:"Trincomalee" },
    { discode:"KUR" , district:"Kurunegala" },
    { discode:"PUT" , district:"Puttalam" },
    { discode:"ANU" , district:"Anuradhapura" },
    { discode:"POL" , district:"Polonnaruwa" },
    { discode:"BAD" , district:"Badulla" },
    { discode:"MON" , district:"Moneragala" },
    { discode:"RAT" , district:"Rathnapura" },
    { discode:"KEG" , district:"Kegalle" },
];

export const LOCATIONS:LocationsType = 
{
    Colombo :
    [
    { value:"COL0" , label:"Colombo" },
    { value:"COL1" , label:"Kolonnawa" },
    { value:"COL2" , label:"Kaduwela" },
    { value:"COL3" , label:"Homagama" },
    { value:"COL4" , label:"Seethawaka" },
    { value:"COL5" , label:"Padukka" },
    { value:"COL6" , label:"Maharagama" },
    { value:"COL7" , label:"Sri Jayawardanapura Kotte" },
    { value:"COL8" , label:"Thimbirigasyaya" },
    { value:"COL9" , label:"Dehiwala" },
    { value:"COL10" , label:"Ratmalana" },
    { value:"COL11" , label:"Moratuwa" },
    { value:"COL12" , label:"Kesbewa" },
    ],
    Gampaha :
    [
    { value:"GAM0" , label:"Negombo" },
    { value:"GAM1" , label:"Katana" },
    { value:"GAM2" , label:"Divulapitiya" },
    { value:"GAM3" , label:"Mirigama" },
    { value:"GAM4" , label:"Minuwangoda" },
    { value:"GAM5" , label:"Wattala" },
    { value:"GAM6" , label:"Ja-Ela" },
    { value:"GAM7" , label:"Gampaha" },
    { value:"GAM8" , label:"Attanagalla" },
    { value:"GAM9" , label:"Dompe" },
    { value:"GAM10" , label:"Mahara" },
    { value:"GAM11" , label:"Kelaniya" },
    { value:"GAM12" , label:"Biyagama" },
    ],
    Kalutara :
    [
    { value:"KAL0" , label:"Panadura" },
    { value:"KAL1" , label:"Bandaragama" },
    { value:"KAL2" , label:"Horana" },
    { value:"KAL3" , label:"Ingiriya" },
    { value:"KAL4" , label:"Bulathsinhala" },
    { value:"KAL5" , label:"Madurawala" },
    { value:"KAL6" , label:"Millaniya" },
    { value:"KAL7" , label:"Kalutara" },
    { value:"KAL8" , label:"Beruwala" },
    { value:"KAL9" , label:"Dodangoda" },
    { value:"KAL10" , label:"Mathugama" },
    { value:"KAL11" , label:"Agalawatta" },
    { value:"KAL12" , label:"Palindanuwara" },
    { value:"KAL13" , label:"Walallawita" },
    ],
    Kandy :
    [
    { value:"KAN0" , label:"Thumpane" },
    { value:"KAN1" , label:"Pujapitiya" },
    { value:"KAN2" , label:"Akurana" },
    { value:"KAN3" , label:"Pathadumbara" },
    { value:"KAN4" , label:"Panvila" },
    { value:"KAN5" , label:"Udadumbara" },
    { value:"KAN6" , label:"Minipe" },
    { value:"KAN7" , label:"Medadumbara" },
    { value:"KAN8" , label:"Kundasale" },
    { value:"KAN9" , label:"Kandy Four Gravets & Gangawata Korale" },
    { value:"KAN10" , label:"Harispattuwa" },
    { value:"KAN11" , label:"Hatharaliyadda" },
    { value:"KAN12" , label:"Yatinuwara" },
    { value:"KAN13" , label:"Udunuwara" },
    { value:"KAN14" , label:"Doluwa" },
    { value:"KAN15" , label:"Pathahewaheta" },
    { value:"KAN16" , label:"Delthota" },
    { value:"KAN17" , label:"Udapalatha" },
    { value:"KAN18" , label:"Ganga Ihala Korale" },
    { value:"KAN19" , label:"Pasbage Korale" },
    ],
    Matale :
    [
    { value:"MAT0" , label:"Galewela" },
    { value:"MAT1" , label:"Dambulla" },
    { value:"MAT2" , label:"Naula" },
    { value:"MAT3" , label:"Pallepola" },
    { value:"MAT4" , label:"Yatawatta " },
    { value:"MAT5" , label:"Yatawatta" },
    { value:"MAT6" , label:"Matale" },
    { value:"MAT7" , label:"Ambanganga Korale" },
    { value:"MAT8" , label:"Laggala-Pallegama" },
    { value:"MAT9" , label:"Wilgamuwa" },
    { value:"MAT10" , label:"Rattota" },
    { value:"MAT11" , label:"Ukuwela" },
    ],
    NuwaraEliya :
    [
    { value:"NUW0" , label:"Kothmale" },
    { value:"NUW1" , label:"Hanguranketha" },
    { value:"NUW2" , label:"Walapane" },
    { value:"NUW3" , label:"Nuwara Eliya" },
    { value:"NUW4" , label:"Ambagamuwa" },
    ],
    Galle :
    [
    { value:"GAL0" , label:"Bentota" },
    { value:"GAL1" , label:"Balapitiya" },
    { value:"GAL2" , label:"Karandeniya" },
    { value:"GAL3" , label:"Elpitiya" },
    { value:"GAL4" , label:"Niyagama" },
    { value:"GAL5" , label:"Thawalama" },
    { value:"GAL6" , label:"Neluwa" },
    { value:"GAL7" , label:"Nagoda" },
    { value:"GAL8" , label:"Baddegama" },
    { value:"GAL9" , label:"Wanduramba" },
    { value:"GAL10" , label:"Welivitiya-Divithura" },
    { value:"GAL11" , label:"Ambalangoda" },
    { value:"GAL12" , label:"Gonapeenuwala" },
    { value:"GAL13" , label:"Madampagama" },
    { value:"GAL14" , label:"Hikkaduwa" },
    { value:"GAL15" , label:"Rathgama" },
    { value:"GAL16" , label:"Galle Four Gravets" },
    { value:"GAL17" , label:"Bope-Poddala" },
    { value:"GAL18" , label:"Akmeemana" },
    { value:"GAL19" , label:"Yakkalamulla" },
    { value:"GAL20" , label:"Imaduwa" },
    { value:"GAL21" , label:"Habaraduwa" },
    ],
    Matara :
    [
    { value:"MTA0" , label:"Pitabeddara" },
    { value:"MTA1" , label:"Kotapola" },
    { value:"MTA2" , label:"Pasgoda" },
    { value:"MTA3" , label:"Mulatiyana" },
    { value:"MTA4" , label:"Athuraliya" },
    { value:"MTA5" , label:"Akurassa" },
    { value:"MTA6" , label:"Welipitiya" },
    { value:"MTA7" , label:"Malimbada" },
    { value:"MTA8" , label:"Kamburupitiya" },
    { value:"MTA9" , label:"Hakmana" },
    { value:"MTA10" , label:"Kirinda -Puhulwella" },
    { value:"MTA11" , label:"Thihagoda" },
    { value:"MTA12" , label:"Weligama" },
    { value:"MTA13" , label:"Matara Four Gravets" },
    { value:"MTA14" , label:"Devinuwara" },
    { value:"MTA15" , label:"Dickwella" },
    ],
    Hambantota :
    [
    { value:"HAM0" , label:"Sooriyawewa" },
    { value:"HAM1" , label:"Lunugamvehera" },
    { value:"HAM2" , label:"Thissamaharama" },
    { value:"HAM3" , label:"Tissamaharamaya" },
    { value:"HAM4" , label:"Hambantota" },
    { value:"HAM5" , label:"Ambalantota" },
    { value:"HAM6" , label:"Angunakolapelessa" },
    { value:"HAM7" , label:"Weeraketiya" },
    { value:"HAM8" , label:"Katuwana" },
    { value:"HAM9" , label:"Walasmulla" },
    { value:"HAM10" , label:"Okewela" },
    { value:"HAM11" , label:"Beliatta" },
    { value:"HAM12" , label:"Tangalle" },
    ],
    Jaffna :
    [
    { value:"JAF0" , label:"Island North (Kayts)" },
    { value:"JAF1" , label:"Karainagar" },
    { value:"JAF2" , label:"Valikamam West" },
    { value:"JAF3" , label:"Valikamam South West (Sandilipay)" },
    { value:"JAF4" , label:"Valikamam North" },
    { value:"JAF5" , label:"Valikamam South (Uduvil)" },
    { value:"JAF6" , label:"Valikamam East (Kopay)" },
    { value:"JAF7" , label:"Vadamaradchi South-West (Karaveddy)" },
    { value:"JAF8" , label:"Vadamaradchy East" },
    { value:"JAF9" , label:"Vadamaradchi North (Point Pedro)" },
    { value:"JAF10" , label:"Thenmaradchi" },
    { value:"JAF11" , label:"Nallur" },
    { value:"JAF12" , label:"Jaffna" },
    { value:"JAF13" , label:"Island South (Velanai)" },
    { value:"JAF14" , label:"Delft" },
    ],
    Mannar :
    [
    { value:"MAN0" , label:"Mannar Town" },
    { value:"MAN1" , label:"Manthai West" },
    { value:"MAN2" , label:"Madhu" },
    { value:"MAN3" , label:"Nanattan" },
    { value:"MAN4" , label:"Musali" },
    ],
    Vavuniya :
    [
    { value:"VAV0" , label:"Vavuniya North" },
    { value:"VAV1" , label:"Vavuniya South" },
    { value:"VAV2" , label:"Vavuniya Town" },
    { value:"VAV3" , label:"Vengalacheddikulam" },
    ],
    Mullaitivu :
    [
    { value:"MUL0" , label:"Thunukkai" },
    { value:"MUL1" , label:"Manthai East" },
    { value:"MUL2" , label:"Puthukudiyiruppu" },
    { value:"MUL3" , label:"Oddusuddan" },
    { value:"MUL4" , label:"Meritimepattu" },
    { value:"MUL5" , label:"Welioya" },
    ],
    Kilinochchi :
    [
    { value:"KIL0" , label:"Pachchilaipalli" },
    { value:"KIL1" , label:"Kandawalai" },
    { value:"KIL2" , label:"Karachchi" },
    { value:"KIL3" , label:"Poonakary" },
    ],
    Batticaloa :
    [
    { value:"BAT0" , label:"Koralai Pattu North (Vaharai)" },
    { value:"BAT1" , label:"Koralai Pattu Central" },
    { value:"BAT2" , label:"Koralaipattu West (Oddamavadi)" },
    { value:"BAT3" , label:"Koralai Pattu(Valachchenai)" },
    { value:"BAT4" , label:"Koralai Pattu South (Kiran)" },
    { value:"BAT5" , label:"Eravur Pattu" },
    { value:"BAT6" , label:"Eravur Town" },
    { value:"BAT7" , label:"Manmunai North" },
    { value:"BAT8" , label:"Manmunai West" },
    { value:"BAT9" , label:"Kattankudy" },
    { value:"BAT10" , label:"Manmunai Pattu(Araipattai)" },
    { value:"BAT11" , label:"Manmunai South-West" },
    { value:"BAT12" , label:"Poratheevu Pattu" },
    { value:"BAT13" , label:"Pratheevu Pattu" },
    { value:"BAT14" , label:"Manmunai South & Eruvil pattu" },
    ],
    Ampara :
    [
    { value:"AMP0" , label:"Dehiattakandiya" },
    { value:"AMP1" , label:"Padiyathalawa" },
    { value:"AMP2" , label:"Mahaoya" },
    { value:"AMP3" , label:"Uhana" },
    { value:"AMP4" , label:"Ampara" },
    { value:"AMP5" , label:"Navithanveli" },
    { value:"AMP6" , label:"Sammanthurai" },
    { value:"AMP7" , label:"Kalmunai Tamil Division" },
    { value:"AMP8" , label:"Kalmunai" },
    { value:"AMP9" , label:"Sainthamaruthu" },
    { value:"AMP10" , label:"Karaitheevu" },
    { value:"AMP11" , label:"Ninthavur" },
    { value:"AMP12" , label:"Addalachchenai" },
    { value:"AMP13" , label:"Irakkamam" },
    { value:"AMP14" , label:"Akkaraipattu" },
    { value:"AMP15" , label:"Akkaraipattu " },
    { value:"AMP16" , label:"Alayadiwembu" },
    { value:"AMP17" , label:"Damana" },
    { value:"AMP18" , label:"Thirukkovil" },
    { value:"AMP19" , label:"Pottuvil" },
    { value:"AMP20" , label:"Lahugala" },
    ],
    Trincomalee :
    [
    { value:"TRI0" , label:"Padavisiripura" },
    { value:"TRI1" , label:"Kuchchaveli" },
    { value:"TRI2" , label:"Gomarankadawala" },
    { value:"TRI3" , label:"Morawewa" },
    { value:"TRI4" , label:"Trincomalee Town and Gravets" },
    { value:"TRI5" , label:"Thambalagamuwa" },
    { value:"TRI6" , label:"Kanthale" },
    { value:"TRI7" , label:"Kinniya" },
    { value:"TRI8" , label:"Muttur" },
    { value:"TRI9" , label:"Seruvila" },
    { value:"TRI10" , label:"Verugal(Eachchilampattu)" },
    ],
    Kurunegala :
    [
    { value:"KUR0" , label:"Giribawa" },
    { value:"KUR1" , label:"Galgamuwa" },
    { value:"KUR2" , label:"Ehetuwewa" },
    { value:"KUR3" , label:"Ambanpola" },
    { value:"KUR4" , label:"Kotavehera" },
    { value:"KUR5" , label:"Rasnayakapura" },
    { value:"KUR6" , label:"Nikaweratiya" },
    { value:"KUR7" , label:"Maho" },
    { value:"KUR8" , label:"Polpithigama" },
    { value:"KUR9" , label:"Ibbagamuwa" },
    { value:"KUR10" , label:"Ganewatta" },
    { value:"KUR11" , label:"Wariyapola" },
    { value:"KUR12" , label:"Kobeigane" },
    { value:"KUR13" , label:"Bingiriya" },
    { value:"KUR14" , label:"Panduwasnuwara West" },
    { value:"KUR15" , label:"Panduwasnuwara East" },
    { value:"KUR16" , label:"Bamunakotuwa" },
    { value:"KUR17" , label:"Maspotha" },
    { value:"KUR18" , label:"Kurunegala" },
    { value:"KUR19" , label:"Mallawapitiya" },
    { value:"KUR20" , label:"Mawathagama" },
    { value:"KUR21" , label:"Mawathagama " },
    { value:"KUR22" , label:"Rideegama" },
    { value:"KUR23" , label:"Weerambugedara" },
    { value:"KUR24" , label:"Kuliyapitiya East" },
    { value:"KUR25" , label:"Kuliyapitiya West" },
    { value:"KUR26" , label:"Udubaddawa" },
    { value:"KUR27" , label:"Pannala" },
    { value:"KUR28" , label:"Narammala" },
    { value:"KUR29" , label:"Alawwa" },
    { value:"KUR30" , label:"Polgahawela" },
    ],
    Puttalam :
    [
    { value:"PUT0" , label:"Kalpitiya" },
    { value:"PUT1" , label:"Vanathawilluwa" },
    { value:"PUT2" , label:"Karuwalagaswewa" },
    { value:"PUT3" , label:"Nawagattegama" },
    { value:"PUT4" , label:"Puttalam" },
    { value:"PUT5" , label:"Mundel" },
    { value:"PUT6" , label:"Mahakumbukkadawala" },
    { value:"PUT7" , label:"Anamaduwa" },
    { value:"PUT8" , label:"Pallama" },
    { value:"PUT9" , label:"Arachchikattuwa" },
    { value:"PUT10" , label:"Chilaw" },
    { value:"PUT11" , label:"Madampe" },
    { value:"PUT12" , label:"Mahawewa" },
    { value:"PUT13" , label:"Nattandiya" },
    { value:"PUT14" , label:"Wennappuwa" },
    { value:"PUT15" , label:"Dankotuwa" },
    ],
    Anuradhapura :
    [
    { value:"ANU0" , label:"Padaviya" },
    { value:"ANU1" , label:"Kebithigollewa" },
    { value:"ANU2" , label:"Madawachchiya" },
    { value:"ANU3" , label:"Medawachchiya" },
    { value:"ANU4" , label:"Mahawilachchiya" },
    { value:"ANU5" , label:"Nuwaragam Palatha Central" },
    { value:"ANU6" , label:"Rambewa" },
    { value:"ANU7" , label:"Kahatagasdigiliya" },
    { value:"ANU8" , label:"Horowpothana" },
    { value:"ANU9" , label:"Galenbindunuwewa" },
    { value:"ANU10" , label:"Mihinthale" },
    { value:"ANU11" , label:"Nuwaragam Palatha East" },
    { value:"ANU12" , label:"Nachchadoowa" },
    { value:"ANU13" , label:"Nochchiyagama" },
    { value:"ANU14" , label:"Rajanganaya" },
    { value:"ANU15" , label:"Thambuttegama" },
    { value:"ANU16" , label:"Thalawa" },
    { value:"ANU17" , label:"Thirappane" },
    { value:"ANU18" , label:"Kekirawa" },
    { value:"ANU19" , label:"Palugaswewa" },
    { value:"ANU20" , label:"Ipalogama" },
    { value:"ANU21" , label:"Galnewa" },
    { value:"ANU22" , label:"Palagala" },
    ],
    Polonnaruwa :
    [
    { value:"POL0" , label:"Hingurakgoda" },
    { value:"POL1" , label:"Medirigiriya" },
    { value:"POL2" , label:"Lankapura" },
    { value:"POL3" , label:"Welikanda" },
    { value:"POL4" , label:"Welkanda" },
    { value:"POL5" , label:"Dimbulagala" },
    { value:"POL6" , label:"Thamankaduwa" },
    { value:"POL7" , label:"Elahera" },
    ],
    Badulla :
    [
    { value:"BAD0" , label:"Mahiyanganaya" },
    { value:"BAD1" , label:"Rideemaliyadda" },
    { value:"BAD2" , label:"Meegahakivula" },
    { value:"BAD3" , label:"Kandeketiya" },
    { value:"BAD4" , label:"Soranathota" },
    { value:"BAD5" , label:"Passara" },
    { value:"BAD6" , label:"Lunugala" },
    { value:"BAD7" , label:"Badulla" },
    { value:"BAD8" , label:"Hali Ela" },
    { value:"BAD9" , label:"Uva Paranagama" },
    { value:"BAD10" , label:"Welimada" },
    { value:"BAD11" , label:"Bandarawela" },
    { value:"BAD12" , label:"Ella" },
    { value:"BAD13" , label:"Haputale" },
    { value:"BAD14" , label:"Haputale " },
    { value:"BAD15" , label:"Haldummulla" },
    ],
    Moneragala :
    [
    { value:"MON0" , label:"Bibile" },
    { value:"MON1" , label:"Madulla" },
    { value:"MON2" , label:"Medagama" },
    { value:"MON3" , label:"Siyambalanduwa" },
    { value:"MON4" , label:"Moneragala" },
    { value:"MON5" , label:"Badalkumbura" },
    { value:"MON6" , label:"Wellawaya" },
    { value:"MON7" , label:"Buttala" },
    { value:"MON8" , label:"Katharagama" },
    { value:"MON9" , label:"Thanamalvila" },
    { value:"MON10" , label:"Sevanagala" },
    ],
    Rathnapura :
    [
    { value:"RAT0" , label:"Eheliyagoda" },
    { value:"RAT1" , label:"Kuruvita" },
    { value:"RAT2" , label:"Kiriella" },
    { value:"RAT3" , label:"Kiiriella" },
    { value:"RAT4" , label:"Ratnapura" },
    { value:"RAT5" , label:"Imbulpe" },
    { value:"RAT6" , label:"Balangoda" },
    { value:"RAT7" , label:"Kalthota" },
    { value:"RAT8" , label:"Opanayaka" },
    { value:"RAT9" , label:"Pelmadulla" },
    { value:"RAT10" , label:"Elapatha" },
    { value:"RAT11" , label:"Ayagama" },
    { value:"RAT12" , label:"Kalawana" },
    { value:"RAT13" , label:"Nivitigala" },
    { value:"RAT14" , label:"Kahawatta" },
    { value:"RAT15" , label:"Godakawela" },
    { value:"RAT16" , label:"Weligepola" },
    { value:"RAT17" , label:"Embilipitiya" },
    { value:"RAT18" , label:"Kolonna" },
    ],
    Kegalle :
    [
    { value:"KEG0" , label:"Rambukkana" },
    { value:"KEG1" , label:"Mawanella" },
    { value:"KEG2" , label:"Aranayaka" },
    { value:"KEG3" , label:"Kegalle" },
    { value:"KEG4" , label:"Galigamuwa" },
    { value:"KEG5" , label:"Warakapola" },
    { value:"KEG6" , label:"Ruwanwella" },
    { value:"KEG7" , label:"Bulathkohupitiya" },
    { value:"KEG8" , label:"Yatiyanthota" },
    { value:"KEG9" , label:"Dehiovita" },
    { value:"KEG10" , label:"Deraniyagala" },
    ],
    }